/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jpanel_Form_NhanVien;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Connection.ConnectionDB;
import Entities.HangXe_entity;
import Entities.HoaDon_entity;
import Entities.HopDong_entity;
import Entities.KhachHang_entity;
import Entities.LoaiXe_entity;
import Entities.MauXe_entity;
import Entities.NhanVien_entity;
import Entities.XeMay_entity;
import Jpanel_Form_QuanLy.ThongKe;
import Model.HoaDon_model;
import Model.HopDong_model;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Win 10
 */
public class LapHopDong extends javax.swing.JPanel {

	/**
	 * Creates new form LapHopDong
	 */
	ArrayList<XeMay_entity> ob_id_xe = new ArrayList<>();
	ArrayList<NhanVien_entity> ob_id_nv = new ArrayList<>();
	ArrayList<KhachHang_entity> ob_id_kh = new ArrayList<>();
	ArrayList<HoaDon_entity> ob_id_hd = new ArrayList<>();
	ArrayList<HoaDon_entity> ob_hd = new ArrayList<>();
	ArrayList<HopDong_entity> listHopDong = new ArrayList<>();
	ArrayList<XeMay_entity> xemay = new ArrayList<>();
	ArrayList<HangXe_entity> listHangXe = new ArrayList<>();
	ArrayList<LoaiXe_entity> listLoaiXe = new ArrayList<>();
	ArrayList<MauXe_entity> listMauXe = new ArrayList<>();
        List<HoaDon_entity> ob_xuat = new ArrayList<>();
	Vector data = new Vector();
	HopDong_model hd_md = new HopDong_model();
	DefaultTableModel md2 = new DefaultTableModel();

	public LapHopDong() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThemHopDong = new javax.swing.JButton();
        btnXuatHopDong = new javax.swing.JButton();
        lblTTHoaDon = new javax.swing.JLabel();
        lblThongTinHopDong = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTHD = new javax.swing.JTable();
        pnlTTHopDong = new javax.swing.JPanel();
        pnlThongTinHD = new javax.swing.JPanel();
        lblMaHopDong = new javax.swing.JLabel();
        lblTongTienHD = new javax.swing.JLabel();
        lblNgayLapHD = new javax.swing.JLabel();
        txtMaHopDong = new javax.swing.JTextField();
        jdcNgayLapHD = new com.toedter.calendar.JDateChooser();
        txtTongTienHD = new javax.swing.JTextField();
        pnlTTBenBan = new javax.swing.JPanel();
        lblNhanVien1 = new javax.swing.JLabel();
        lblSoCMNDNV = new javax.swing.JLabel();
        lblNgaySinhNV = new javax.swing.JLabel();
        txtSoCMNDNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        jdcNgaySinhNV = new com.toedter.calendar.JDateChooser();
        pnlTTBenMua = new javax.swing.JPanel();
        lblTenKH = new javax.swing.JLabel();
        lblNgaySinhKH = new javax.swing.JLabel();
        lblSoCMNDKH = new javax.swing.JLabel();
        lblDiaChiKH = new javax.swing.JLabel();
        txttenKH = new javax.swing.JTextField();
        jdcNgaySinhKH = new com.toedter.calendar.JDateChooser();
        txtDiaChiKH = new javax.swing.JTextField();
        txtSoCMNDKH = new javax.swing.JTextField();
        lblThongTinBenBan = new javax.swing.JLabel();
        lblThongTinBenMua = new javax.swing.JLabel();
        pnlTTXeMay = new javax.swing.JPanel();
        lblTenXe = new javax.swing.JLabel();
        lblSoKhung = new javax.swing.JLabel();
        lblSoMay = new javax.swing.JLabel();
        lblMauXe = new javax.swing.JLabel();
        lblHangXe = new javax.swing.JLabel();
        lblLoaiXe = new javax.swing.JLabel();
        txtSoMay = new javax.swing.JTextField();
        txtTenXe = new javax.swing.JTextField();
        txtSoKhung = new javax.swing.JTextField();
        txtHangXe = new javax.swing.JTextField();
        txtMauXe = new javax.swing.JTextField();
        txtLoaiXe = new javax.swing.JTextField();
        lblSoMay1 = new javax.swing.JLabel();
        lblDungTich = new javax.swing.JLabel();
        txtGiaXe = new javax.swing.JTextField();
        txtDungTich = new javax.swing.JTextField();
        lblSoLuongXe = new javax.swing.JLabel();
        txtSoLuongXe = new javax.swing.JTextField();
        lblThongTinXeMay = new javax.swing.JLabel();
        btnChonHoaDon = new javax.swing.JButton();
        lblNgayLap = new javax.swing.JLabel();
        jdcNgayLapHoaDon = new com.toedter.calendar.JDateChooser();
        btnNhapLai = new javax.swing.JButton();

        btnThemHopDong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Button-Add-icon.png"))); // NOI18N
        btnThemHopDong.setText("Thêm hợp đồng");
        btnThemHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHopDongActionPerformed(evt);
            }
        });

        btnXuatHopDong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXuatHopDong.setText("Xuất hợp đồng");
        btnXuatHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHopDongActionPerformed(evt);
            }
        });

        lblTTHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTTHoaDon.setForeground(new java.awt.Color(153, 0, 0));
        lblTTHoaDon.setText("Thông tin chi tiết hóa đơn");

        lblThongTinHopDong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblThongTinHopDong.setForeground(new java.awt.Color(153, 0, 0));
        lblThongTinHopDong.setText("Thông tin hợp đồng");

        lblMaHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        lblMaHoaDon.setForeground(new java.awt.Color(0, 51, 0));
        lblMaHoaDon.setText("Mã hóa đơn");

        txtMaHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        tblCTHD.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        tblCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTHD);

        pnlThongTinHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaHopDong.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblMaHopDong.setText("Mã hợp đồng");

        lblTongTienHD.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblTongTienHD.setText("Tổng tiền");

        lblNgayLapHD.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblNgayLapHD.setText("Ngày lập hợp đồng");

        txtMaHopDong.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtTongTienHD.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnlThongTinHDLayout = new javax.swing.GroupLayout(pnlThongTinHD);
        pnlThongTinHD.setLayout(pnlThongTinHDLayout);
        pnlThongTinHDLayout.setHorizontalGroup(
            pnlThongTinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinHDLayout.createSequentialGroup()
                        .addGroup(pnlThongTinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinHDLayout.createSequentialGroup()
                                .addComponent(lblMaHopDong)
                                .addGap(33, 33, 33))
                            .addComponent(lblNgayLapHD, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlThongTinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongTienHD, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcNgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlThongTinHDLayout.createSequentialGroup()
                        .addComponent(lblTongTienHD)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlThongTinHDLayout.setVerticalGroup(
            pnlThongTinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHopDong)
                    .addComponent(txtMaHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcNgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayLapHD))
                .addGroup(pnlThongTinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinHDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTongTienHD)
                        .addGap(58, 58, 58))
                    .addGroup(pnlThongTinHDLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTongTienHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlTTBenBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNhanVien1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblNhanVien1.setText("Nhân viên");

        lblSoCMNDNV.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblSoCMNDNV.setText("Số CMND");

        lblNgaySinhNV.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblNgaySinhNV.setText("Ngày sinh");

        txtSoCMNDNV.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtTenNV.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnlTTBenBanLayout = new javax.swing.GroupLayout(pnlTTBenBan);
        pnlTTBenBan.setLayout(pnlTTBenBanLayout);
        pnlTTBenBanLayout.setHorizontalGroup(
            pnlTTBenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTBenBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTBenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTTBenBanLayout.createSequentialGroup()
                        .addGroup(pnlTTBenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoCMNDNV)
                            .addComponent(lblNhanVien1))
                        .addGroup(pnlTTBenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTTBenBanLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txtSoCMNDNV, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTBenBanLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlTTBenBanLayout.createSequentialGroup()
                        .addComponent(lblNgaySinhNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdcNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlTTBenBanLayout.setVerticalGroup(
            pnlTTBenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTBenBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTBenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhanVien1)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlTTBenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTBenBanLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblNgaySinhNV)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTBenBanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlTTBenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoCMNDNV)
                    .addComponent(txtSoCMNDNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTTBenMua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTenKH.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblTenKH.setText("Khách hàng");

        lblNgaySinhKH.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblNgaySinhKH.setText("Ngày sinh");

        lblSoCMNDKH.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblSoCMNDKH.setText("Số CMND");

        lblDiaChiKH.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblDiaChiKH.setText("Địa chỉ");

        txttenKH.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtDiaChiKH.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtSoCMNDKH.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnlTTBenMuaLayout = new javax.swing.GroupLayout(pnlTTBenMua);
        pnlTTBenMua.setLayout(pnlTTBenMuaLayout);
        pnlTTBenMuaLayout.setHorizontalGroup(
            pnlTTBenMuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTBenMuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTBenMuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenKH)
                    .addComponent(lblNgaySinhKH)
                    .addComponent(lblSoCMNDKH)
                    .addComponent(lblDiaChiKH))
                .addGap(18, 18, 18)
                .addGroup(pnlTTBenMuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcNgaySinhKH, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoCMNDKH, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlTTBenMuaLayout.setVerticalGroup(
            pnlTTBenMuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTBenMuaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlTTBenMuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenKH)
                    .addComponent(txttenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTBenMuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcNgaySinhKH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgaySinhKH, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlTTBenMuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoCMNDKH)
                    .addComponent(txtSoCMNDKH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTTBenMuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaChiKH))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTTHopDongLayout = new javax.swing.GroupLayout(pnlTTHopDong);
        pnlTTHopDong.setLayout(pnlTTHopDongLayout);
        pnlTTHopDongLayout.setHorizontalGroup(
            pnlTTHopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTHopDongLayout.createSequentialGroup()
                .addComponent(pnlThongTinHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTTBenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTTBenMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlTTHopDongLayout.setVerticalGroup(
            pnlTTHopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThongTinHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTTBenBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTTBenMua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblThongTinBenBan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblThongTinBenBan.setForeground(new java.awt.Color(153, 0, 0));
        lblThongTinBenBan.setText("Thông tin bên bán");

        lblThongTinBenMua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblThongTinBenMua.setForeground(new java.awt.Color(153, 0, 0));
        lblThongTinBenMua.setText("Thông tin bên mua");

        pnlTTXeMay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTTXeMay.setPreferredSize(new java.awt.Dimension(678, 221));

        lblTenXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblTenXe.setText("Tên xe");

        lblSoKhung.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblSoKhung.setText("Số khung");

        lblSoMay.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblSoMay.setText("Số máy");

        lblMauXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblMauXe.setText("Màu xe");

        lblHangXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblHangXe.setText("Hãng xe");

        lblLoaiXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblLoaiXe.setText("Loại xe");

        txtSoMay.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtTenXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtSoKhung.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtHangXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtMauXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtLoaiXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        lblSoMay1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblSoMay1.setText("Giá xe");

        lblDungTich.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblDungTich.setText("Dung tích");

        txtGiaXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtDungTich.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        lblSoLuongXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblSoLuongXe.setText("Số lượng");

        txtSoLuongXe.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnlTTXeMayLayout = new javax.swing.GroupLayout(pnlTTXeMay);
        pnlTTXeMay.setLayout(pnlTTXeMayLayout);
        pnlTTXeMayLayout.setHorizontalGroup(
            pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTXeMayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoKhung)
                    .addComponent(lblSoMay)
                    .addComponent(lblTenXe))
                .addGap(65, 65, 65)
                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSoKhung, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addComponent(txtSoMay))
                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLoaiXe)
                        .addComponent(lblHangXe))
                    .addGroup(pnlTTXeMayLayout.createSequentialGroup()
                        .addComponent(lblMauXe)
                        .addGap(6, 6, 6)))
                .addGap(41, 41, 41)
                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoMay1)
                    .addComponent(lblDungTich)
                    .addComponent(lblSoLuongXe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDungTich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuongXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        pnlTTXeMayLayout.setVerticalGroup(
            pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTXeMayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTXeMayLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(pnlTTXeMayLayout.createSequentialGroup()
                        .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlTTXeMayLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lblTenXe))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSoMay1)
                                    .addComponent(txtGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblHangXe, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTXeMayLayout.createSequentialGroup()
                                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSoKhung)
                                    .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDungTich)
                                        .addComponent(txtDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblLoaiXe)
                                        .addComponent(txtLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSoMay)
                                    .addGroup(pnlTTXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblMauXe)
                                        .addComponent(txtMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSoLuongXe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblSoLuongXe, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        lblThongTinXeMay.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblThongTinXeMay.setForeground(new java.awt.Color(153, 0, 0));
        lblThongTinXeMay.setText("Thông tin xe máy");

        btnChonHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnChonHoaDon.setText("Chọn");
        btnChonHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHoaDonActionPerformed(evt);
            }
        });

        lblNgayLap.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblNgayLap.setText("Ngày lập");

        btnNhapLai.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTTHoaDon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblThongTinXeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTTHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblThongTinHopDong)
                        .addGap(236, 236, 236)
                        .addComponent(lblThongTinBenBan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblThongTinBenMua)
                        .addGap(212, 212, 212))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThemHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnXuatHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnChonHoaDon)
                                    .addGap(33, 33, 33)
                                    .addComponent(lblNgayLap)
                                    .addGap(28, 28, 28)
                                    .addComponent(jdcNgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(btnNhapLai))
                                .addComponent(pnlTTXeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChonHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNgayLap))
                    .addComponent(jdcNgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTTHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThongTinHopDong)
                    .addComponent(lblThongTinBenBan)
                    .addComponent(lblThongTinBenMua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTTHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThongTinXeMay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTTXeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHopDong)
                    .addComponent(btnXuatHopDong))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1134, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHoaDonActionPerformed
        // TODO add your handling code here:
        String timMa = txtMaHoaDon.getText().trim();
		if (timMa.equals("")) {
			JOptionPane.showMessageDialog(null, "Chọn mã hóa đơn để lập hợp đồng!", "Thông Báo",
					JOptionPane.INFORMATION_MESSAGE);
		} else {
			laymaCT_HD(timMa);
			thongTinHoaDon(timMa);
			thongTinBenBan(timMa);
			thongTinBenMua(timMa);
		}
    }//GEN-LAST:event_btnChonHoaDonActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        // TODO add your handling code here:
        md2 = new DefaultTableModel();
		tblCTHD.setModel(md2);
		txtMaHoaDon.setText(null);
		txtTenNV.setText(null);
		txtSoCMNDNV.setText(null);
		txttenKH.setText(null);
		txtSoCMNDKH.setText(null);
		txtDiaChiKH.setText(null);
		xoaRongXeMay();
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void tblCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHDMouseClicked
        // TODO add your handling code here:
        int row = tblCTHD.getSelectedRow();
		String tenxe = md2.getValueAt(row, 2).toString();
		String giaxe = md2.getValueAt(row, 3).toString();
		String tongtien = md2.getValueAt(row, 6).toString();
		String soluongxe = md2.getValueAt(row, 4).toString();
		txtTongTienHD.setText(tongtien);
		txtTenXe.setText(tenxe);
		txtGiaXe.setText(giaxe);
		txtSoLuongXe.setText(soluongxe);
		thongTinXeMay(tenxe);
    }//GEN-LAST:event_tblCTHDMouseClicked

    private void btnXuatHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHopDongActionPerformed

        String link = "C:\\Users\\Win 10\\Desktop\\PTUD_2019_Nhom06_DHKTPM13A\\File dong goi\\src\\Ireport\\HopDong.jrxml";
        String mahopdong = txtMaHopDong.getText();
        if (mahopdong.equals("")) {
		JOptionPane.showMessageDialog(null, "Bạn chưa lập hợp đồng!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
	} else{      
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String database = "jdbc:sqlserver://localhost:1433;databaseName=PTUDOfficial";
                String us = "sa";
                String pa = "sapassword";
                Connection coon = (Connection)DriverManager.getConnection(database,us,pa);
                JasperReport jr = JasperCompileManager.compileReport(link);
                JasperPrint jp = JasperFillManager.fillReport(jr, null,coon);
                xoaRongXeMay();
                JasperViewer.viewReport(jp);
        }catch(Exception ex){
            ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnXuatHopDongActionPerformed

	// Các hàm xửa lí

	// Tim hoa don


	public void xoaRongXeMay() {
		txtMaHopDong.setText(null);
		txtTongTienHD.setText(null);
		txtTenXe.setText(null);
		txtSoKhung.setText(null);
		txtSoMay.setText(null);
		txtHangXe.setText(null);
		txtLoaiXe.setText(null);
		txtMauXe.setText(null);
		txtGiaXe.setText(null);
		txtDungTich.setText(null);
		txtSoLuongXe.setText(null);
	}

	public void laymaCT_HD(String mahd) {
		Locale locale = new Locale("vi", "VN");
		NumberFormat fm = NumberFormat.getCurrencyInstance(locale);
		String get_ct_hd = "SELECT * FROM ChiTietHoaDon where maHD='" + mahd + "'";
		Connection conn = ConnectionDB.openConnection();
		Vector col_ct = new Vector();
		data = new Vector();
		int i = 1;
		col_ct.add("STT");
		col_ct.add("Mã hóa đơn");
		col_ct.add("Tên xe máy");
		col_ct.add("Đơn giá");
		col_ct.add("Số lượng");
		col_ct.add("Lệ phí trước bạ");
		col_ct.add("Thành tiền");
		try {
			PreparedStatement pst = conn.prepareCall(get_ct_hd);
			ResultSet rs = pst.executeQuery();
			while (rs.next()) {
				Vector row_vl = new Vector();
				row_vl.add(i++);
				row_vl.add(rs.getString("maHD"));
				ob_id_xe = hd_md.getIDxe(rs.getString("maXe"));
				row_vl.add(ob_id_xe.get(0).getTenXe());
				row_vl.add(fm.format(rs.getFloat("donGia")));
				row_vl.add(rs.getInt("soLuong"));
				row_vl.add(fm.format(rs.getInt("thueXe")));
				row_vl.add(fm.format(rs.getFloat("thanhTien")));
				data.add(row_vl);
			}
		} catch (SQLException ex) {
			Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
		}
		md2 = new DefaultTableModel(data, col_ct);
		tblCTHD.setModel(md2);

	}

	public void thongTinHoaDon(String mahd) {
		Locale locale = new Locale("vi", "VN");
		NumberFormat fm = NumberFormat.getCurrencyInstance(locale);
		String gethd = "SELECT * FROM HoaDon where maHD='" + mahd + "'";
		Connection conn = ConnectionDB.openConnection();
		Vector col_ct = new Vector();
		data = new Vector();
		try {
			PreparedStatement pst = conn.prepareCall(gethd);
			ResultSet rs = pst.executeQuery();
			while (rs.next()) {
				// Hóa đơn
				ob_id_hd = hd_md.getIDHD(rs.getString("maHD"));
			}
		} catch (SQLException ex) {
			Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
		}

		Date date = null;
		try {
			date = new SimpleDateFormat("yyyy-MM-dd").parse((String) ob_id_hd.get(0).getNgayLapHoaDon());
			jdcNgayLapHoaDon.setDate(date);
		} catch (ParseException ex) {
			Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	public void thongTinBenBan(String mahd) {
		Locale locale = new Locale("vi", "VN");
		NumberFormat fm = NumberFormat.getCurrencyInstance(locale);
		String gethd = "SELECT * FROM HoaDon where maHD='" + mahd + "'";
		Connection conn = ConnectionDB.openConnection();
		Vector col_ct = new Vector();
		data = new Vector();
		try {
			PreparedStatement pst = conn.prepareCall(gethd);
			ResultSet rs = pst.executeQuery();
			while (rs.next()) {
				// Nhân viên
				ob_id_nv = hd_md.getIDNV(rs.getString("maNV"));
				txtTenNV.setText(ob_id_nv.get(0).getHoTen());
				txtSoCMNDNV.setText(ob_id_nv.get(0).getSoCMND());
			}
		} catch (SQLException ex) {
			Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
		}
		Date date = null;
		try {
			date = new SimpleDateFormat("yyyy-MM-dd").parse((String) ob_id_nv.get(0).getNgaySinh());
			jdcNgaySinhNV.setDate(date);
		} catch (ParseException ex) {
			Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	public void thongTinBenMua(String mahd) {
		Locale locale = new Locale("vi", "VN");
		NumberFormat fm = NumberFormat.getCurrencyInstance(locale);
		String gethd = "SELECT * FROM HoaDon where maHD='" + mahd + "'";
		Connection conn = ConnectionDB.openConnection();
		Vector col_ct = new Vector();
		data = new Vector();
		try {
			PreparedStatement pst = conn.prepareCall(gethd);
			ResultSet rs = pst.executeQuery();
			while (rs.next()) {
				// Khách hàng
				ob_id_kh = hd_md.getIDKH(rs.getString("maKH"));
				txttenKH.setText(ob_id_kh.get(0).getHoTenKH());
				txtSoCMNDKH.setText(ob_id_kh.get(0).getSoCMND());
				txtDiaChiKH.setText(ob_id_kh.get(0).getDiachi());
			}
		} catch (SQLException ex) {
			Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
		}
		Date date = null;
		try {
			date = new SimpleDateFormat("yyyy-MM-dd").parse((String) ob_id_kh.get(0).getNgaySinh());
			jdcNgaySinhKH.setDate(date);
		} catch (ParseException ex) {
			Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	private void thongTinXeMay(String tenxe) {
		Locale locale = new Locale("vi", "VN");
		NumberFormat fm = NumberFormat.getCurrencyInstance(locale);
		String getXe = "SELECT * FROM XeMay where tenXe='" + tenxe + "'";
		Connection conn = ConnectionDB.openConnection();
		Vector col_ct = new Vector();
		data = new Vector();
		try {
			PreparedStatement pst = conn.prepareCall(getXe);
			ResultSet rs = pst.executeQuery();
			while (rs.next()) {
				xemay = hd_md.getIDTenXe(rs.getString("tenXe"));
				txtSoKhung.setText(xemay.get(0).getSoKhung());
				txtSoMay.setText(xemay.get(0).getSoMay());
				int dt = (int) xemay.get(0).getDungTich();
				txtDungTich.setText(String.valueOf(dt));
				listHangXe = hd_md.getIDHang(rs.getString("maHangXe"));
				txtHangXe.setText(listHangXe.get(0).getTenHang());
				listLoaiXe = hd_md.getIDLoai(rs.getString("maLoaiXe"));
				txtLoaiXe.setText(listLoaiXe.get(0).getTenLoaiXe());
				listMauXe = hd_md.getIDMau(rs.getString("maMauXe"));
				txtMauXe.setText(listMauXe.get(0).getTenMau());
			}
		} catch (SQLException ex) {
			Logger.getLogger(LapHopDong.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	// THÊM HỢP ĐỒNG
	private void btnThemHopDongActionPerformed(java.awt.event.ActionEvent evt) {
		listHopDong = hd_md.get_hd();
		String maHoadon = txtMaHoaDon.getText();
		String maHopDong = txtMaHopDong.getText();
		Date date = jdcNgayLapHD.getDate();
		String date_input = new SimpleDateFormat("yyyy-MM-dd").format(date);

		HopDong_entity hd_et = new HopDong_entity();
		hd_et.setMaHopDong("");
		hd_et.setMaHoaDon(maHoadon);
		hd_et.setNgayLapHopdong(date_input);
		int row = tblCTHD.getSelectedRow();
		if (maHoadon.equals("")) {
			JOptionPane.showMessageDialog(null, "Bạn chưa chọn hóa đơn", "LỖI", JOptionPane.ERROR_MESSAGE);
		} else {
			if(row == -1) {
				JOptionPane.showMessageDialog(null,"Chọn xe máy muốn thêm hợp đồng","Lỗi",JOptionPane.ERROR_MESSAGE);
			}
			else {
				if (hd_md.add_hd(hd_et)) {
					JOptionPane.showMessageDialog(null, "Thêm thành công", "THÀNH CÔNG", JOptionPane.INFORMATION_MESSAGE);
					hienMaHopDong();
				} else {
					JOptionPane.showMessageDialog(null, "Lỗi thông tin thêm", "LỖI", JOptionPane.ERROR_MESSAGE);
				}
			}

		}

	}
    public void hienMaHopDong() {
        listHopDong = hd_md.get_hd();
        for (HopDong_entity ob : listHopDong) {
            txtMaHopDong.setText(ob.getMaHopDong());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonHoaDon;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnThemHopDong;
    private javax.swing.JButton btnXuatHopDong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcNgayLapHD;
    private com.toedter.calendar.JDateChooser jdcNgayLapHoaDon;
    private com.toedter.calendar.JDateChooser jdcNgaySinhKH;
    private com.toedter.calendar.JDateChooser jdcNgaySinhNV;
    private javax.swing.JLabel lblDiaChiKH;
    private javax.swing.JLabel lblDungTich;
    private javax.swing.JLabel lblHangXe;
    private javax.swing.JLabel lblLoaiXe;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaHopDong;
    private javax.swing.JLabel lblMauXe;
    private javax.swing.JLabel lblNgayLap;
    private javax.swing.JLabel lblNgayLapHD;
    private javax.swing.JLabel lblNgaySinhKH;
    private javax.swing.JLabel lblNgaySinhNV;
    private javax.swing.JLabel lblNhanVien1;
    private javax.swing.JLabel lblSoCMNDKH;
    private javax.swing.JLabel lblSoCMNDNV;
    private javax.swing.JLabel lblSoKhung;
    private javax.swing.JLabel lblSoLuongXe;
    private javax.swing.JLabel lblSoMay;
    private javax.swing.JLabel lblSoMay1;
    private javax.swing.JLabel lblTTHoaDon;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTenXe;
    private javax.swing.JLabel lblThongTinBenBan;
    private javax.swing.JLabel lblThongTinBenMua;
    private javax.swing.JLabel lblThongTinHopDong;
    private javax.swing.JLabel lblThongTinXeMay;
    private javax.swing.JLabel lblTongTienHD;
    private javax.swing.JPanel pnlTTBenBan;
    private javax.swing.JPanel pnlTTBenMua;
    private javax.swing.JPanel pnlTTHopDong;
    private javax.swing.JPanel pnlTTXeMay;
    private javax.swing.JPanel pnlThongTinHD;
    private javax.swing.JTable tblCTHD;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtDungTich;
    private javax.swing.JTextField txtGiaXe;
    private javax.swing.JTextField txtHangXe;
    private javax.swing.JTextField txtLoaiXe;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaHopDong;
    private javax.swing.JTextField txtMauXe;
    private javax.swing.JTextField txtSoCMNDKH;
    private javax.swing.JTextField txtSoCMNDNV;
    private javax.swing.JTextField txtSoKhung;
    private javax.swing.JTextField txtSoLuongXe;
    private javax.swing.JTextField txtSoMay;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtTongTienHD;
    private javax.swing.JTextField txttenKH;
    // End of variables declaration//GEN-END:variables
}
