  /*
 * Author: Mai Thị Thanh Thúy
 */
package Jpanel_Form_NhanVien;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Vector;


import javax.swing.table.DefaultTableModel;

import Entities.KhachHang_entity;
import GUI_Form.DangNhap;
import Model.khachHang_model;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author phanb
 */
public class QuanLyKH extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKH
     */
    Connection conn;
    PreparedStatement stmt;
    DefaultTableModel md = new DefaultTableModel();
    khachHang_model kh_md = new khachHang_model();
    ArrayList<KhachHang_entity> kh_en = new ArrayList<>();
    public QuanLyKH() {
        initComponents();
        getDL();
        
    }
    public void getDL(){
        kh_en = kh_md.getData();
        Vector col = new Vector();
        col.addElement("Mã khách hàng");
        col.addElement("Họ tên khách hàng");
        col.addElement("Số CMND");
        col.addElement("Giới tính");
        col.addElement("Ngày sinh");
        col.addElement("Email");
        col.addElement("Số điện thoại");
        col.addElement("Địa chỉ");
        Vector data = new Vector();
        for(KhachHang_entity obs : kh_en){
            Vector row = new Vector();
            row.add(obs.getMaKH());
            row.add(obs.getHoTenKH());
            row.add(obs.getSoCMND());
            if(obs.isGioiTinh()==true){
             row.add("Nam");   
            }else{
                row.add("Nữ");
            }
            row.add(obs.getNgaySinh());
            //SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
            row.add(obs.getEmail());
            row.add(obs.getSoDienThoai());
            row.add(obs.getDiachi());
            data.add(row);
        }
        md = new DefaultTableModel(data,col);
        tblKh.setModel(md);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGioiTinh = new javax.swing.ButtonGroup();
        tbLoiNhap = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        lblMaKH = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblSoCMND = new javax.swing.JLabel();
        lblSoDT = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNamSinh = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKh = new javax.swing.JTable();

        javax.swing.GroupLayout tbLoiNhapLayout = new javax.swing.GroupLayout(tbLoiNhap.getContentPane());
        tbLoiNhap.getContentPane().setLayout(tbLoiNhapLayout);
        tbLoiNhapLayout.setHorizontalGroup(
            tbLoiNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        tbLoiNhapLayout.setVerticalGroup(
            tbLoiNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMaKH.setText("Mã khách hàng");

        lblHoTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHoTen.setText("Họ tên");

        lblSoCMND.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSoCMND.setText("Số CMND");

        lblSoDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSoDT.setText("Số điện thoại");

        lblDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDiaChi.setText("Địa chỉ");

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        lblGioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGioiTinh.setText("Giới tính");

        lblNamSinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNamSinh.setText("Năm sinh");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnGroupGioiTinh.add(radNam);
        radNam.setText("Nam");

        btnGroupGioiTinh.add(radNu);
        radNu.setText("Nữ");
        radNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSoCMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaChi)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtHoTen)
                            .addComponent(txtCMND)
                            .addComponent(txtSoDT))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamSinh))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(radNam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radNu)))
                                .addGap(104, 104, 104)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaKH)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGioiTinh)
                    .addComponent(radNam)
                    .addComponent(radNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoCMND)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamSinh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoDT)))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCapNhat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Actions-document-edit-icon.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoaTrang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit-clear.png"))); // NOI18N
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblKh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Số CMND", "Năm sinh", "Giới tính", "Số điện thoại", "Email", "Địa chỉ"
            }
        ));
        tblKh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
 
    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void radNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        kh_en=kh_md.getData();
        KhachHang_entity kh_ent1 = new KhachHang_entity();
        String ten = txtHoTen.getText();
        String cmnd = txtCMND.getText();
        boolean gioiTinh;
        if(radNam.isSelected()){
            gioiTinh = true;
        }
        else{
            gioiTinh = false;
        }
        Date ngaySinh = jDateChooser1.getDate();
        String ngaySinh_input = new SimpleDateFormat("yyyy-MM-dd").format(ngaySinh);
        String email = txtEmail.getText();
        String soDT = txtSoDT.getText();
        String dc = txtDiaChi.getText();
        boolean check = true;
        int row = tblKh.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null,"Bạn cần chọn khách hàng cần thay đổi thông tin","LỖI",JOptionPane.ERROR_MESSAGE);
            check=false;
        }else {
        	if(kiemTraDL()) {
            	if(check == true){
                    kh_ent1.setHoTenKH(ten);
                    kh_ent1.setSoCMND(cmnd);
                    kh_ent1.setGioiTinh(gioiTinh);
                    kh_ent1.setNgaySinh(ngaySinh_input);
                    kh_ent1.setEmail(email);
                    kh_ent1.setSoDienThoai(soDT);
                    kh_ent1.setDiachi(dc);
                    kh_ent1.setMaKH(kh_en.get(row).getMaKH());
                try {
                    if(kh_md.capNhatKhachHang(kh_ent1)){
                        JOptionPane.showMessageDialog(null,"Cập nhật thành công","THÀNH CÔNG",JOptionPane.INFORMATION_MESSAGE);
                        btnXoaTrangActionPerformed(evt);
                        getDL();
                    }else{
                        JOptionPane.showMessageDialog(null,"Lỗi sai thông tin khách hàng","LỖI",JOptionPane.ERROR_MESSAGE);
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyKH.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        	}
        }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tblKhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhMouseClicked
        // TODO add your handling code here:
        Locale locale = new Locale("vi", "VN");
        txtMaKH.setEditable(false);
        txtMaKH.setForeground(Color.red);
        txtMaKH.setBackground(new java.awt.Color(153, 153, 153));
        NumberFormat fmx = NumberFormat.getCurrencyInstance(locale);
        NumberFormat fm = new DecimalFormat("#,###,###");
        kh_en = kh_md.getData();
        int row = tblKh.getSelectedRow();
        String makh = md.getValueAt(row,0).toString();
        String hoten = md.getValueAt(row, 1).toString();
        String cmnd = md.getValueAt(row,2).toString();
        String gioiTinh = md.getValueAt(row,3).toString();
        Date date = null;
        try{
            date = new SimpleDateFormat("dd-MM-yyyy").parse((String) kh_en.get(row).getNgaySinh());
            jDateChooser1.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyKH.class.getName()).log(Level.SEVERE, null, ex);
        }
        String email  = md.getValueAt(row,5).toString();
        String sdt = md.getValueAt(row,6).toString();
        String dc = md.getValueAt(row,7).toString();
        
        
        txtMaKH.setText(makh);
        txtHoTen.setText(hoten);
        txtCMND.setText(cmnd);
        txtEmail.setText(email);
        txtDiaChi.setText(dc);
        txtSoDT.setText(sdt);
        if(gioiTinh.equalsIgnoreCase("Nam")){
            radNam.setSelected(true);
            
        }else{
            radNu.setSelected(true);
        }     
    }//GEN-LAST:event_tblKhMouseClicked

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
    	txtMaKH.setEditable(true);
    	txtMaKH.setForeground(Color.BLACK);
    	txtMaKH.setBackground(new java.awt.Color(255, 255, 255));
    	txtMaKH.setText("");
        txtHoTen.setText("");
        txtCMND.setText("");
        txtEmail.setText("");
        txtSoDT.setText("");
        txtDiaChi.setText("");        
    }//GEN-LAST:event_btnXoaTrangActionPerformed

	/**
	 * KIỂM TRA DỮ LIỆU.
	 * 
	 * @return
	 */
	public boolean kiemTraDL() {
		String sdt = txtSoDT.getText().trim();
		String cmnd = txtCMND.getText().trim();
		String email = txtEmail.getText().trim();
		// Số điện thoại gồm 10 chữ số
		if (!(sdt.length() > 0 && sdt.matches("\\d{10}"))) {
			JOptionPane.showMessageDialog(null, "Lỗi : Nhập số điện thoại sai định dạng!!!\n Điện thoại gồm 10 chữ số");
			return false;
		}
		if (!(cmnd.length() > 0 && cmnd.matches("\\d{9}"))) {
			JOptionPane.showMessageDialog(null, "Lỗi : Nhập số Chứng minh nhân dân sai định dạng!!!\n Chứng minh nhân dân gồm 9 chữ số");
			return false;
		}
		String EMAIL_REGEX = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
	            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
		if (!(email.length() > 0 && email.matches(EMAIL_REGEX))) {
			JOptionPane.showMessageDialog(null, "Lỗi : Nhập địa chỉ email sai định dạng!!!\nĐịa chỉ Email theo mẫu sau: xxx@xxx.com");
			return false;
		}
		return true;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.ButtonGroup btnGroupGioiTinh;
    private javax.swing.JButton btnXoaTrang;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblNamSinh;
    private javax.swing.JLabel lblSoCMND;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JDialog tbLoiNhap;
    private javax.swing.JTable tblKh;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSoDT;
    // End of variables declaration//GEN-END:variables
}
