/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jpanel_Form_NhanVien;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import Entities.KhachHang_entity;
import Model.khachHang_model;
import java.util.Calendar;

/**
 *
 * @author Win 10
 */
public class ThemKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form ThemKhachHang
     */
	khachHang_model kh_md = new khachHang_model();
//	HoaDon hd = new HoaDon();
    public ThemKhachHang() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnThemKH = new javax.swing.JButton();
        txtHoTen = new javax.swing.JTextField();
        txtSoCMND = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        lblThemMoiKH = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblSoCMND = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblDC = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThemKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/btn_add.png"))); // NOI18N
        btnThemKH.setText("Thêm khách hàng");
        btnThemKH.setPreferredSize(new java.awt.Dimension(135, 33));

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N


        txtSoCMND.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        radNam.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        radNam.setText("Nam");

        radNu.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        radNu.setText("Nữ");

        lblThemMoiKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblThemMoiKH.setForeground(new java.awt.Color(153, 0, 0));
        lblThemMoiKH.setText("THÊM MỚI MỘT KHÁCH HÀNG");

        lblHoTen.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblHoTen.setText("Họ tên");

        lblSoCMND.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblSoCMND.setText("Số CMND");

        lblSDT.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblSDT.setText("Số điện thoại");

        lblDC.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblDC.setText("Địa chỉ");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblEmail.setText("Email");

        lblGioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblGioiTinh.setText("Giới tính");

        lblNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblNgaySinh.setText("Ngày sinh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(lblThemMoiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTen)
                    .addComponent(lblSoCMND)
                    .addComponent(lblSDT)
                    .addComponent(lblDC)
                    .addComponent(lblEmail)
                    .addComponent(lblGioiTinh)
                    .addComponent(lblNgaySinh))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDiaChi)
                        .addComponent(txtEmail)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(radNam)
                            .addGap(26, 26, 26)
                            .addComponent(radNu))
                        .addComponent(jdcNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addComponent(txtHoTen)
                        .addComponent(txtSoCMND)
                        .addComponent(txtSDT)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblThemMoiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoCMND)
                    .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDC)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinh)
                    .addComponent(radNam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radNu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgaySinh)
                    .addComponent(jdcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnThemActionPerformed(evt);
            }
        });
        pack();
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemKhachHang().setVisible(true);
            }
        });
        
    }
    public void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        boolean check = true;
        KhachHang_entity kh_en = new KhachHang_entity();
        String ho_Ten = txtHoTen.getText();
        String cmnd = txtSoCMND.getText();
        boolean gioiTinh;
        if(radNam.isSelected()){
            gioiTinh = true;
        }
        else{
            gioiTinh = false;
        }
        Date namSinh = jdcNgaySinh.getDate();
        String namSinh_input = new SimpleDateFormat("yyyy-MM-dd").format(namSinh);
        String email = txtEmail.getText();
        String soDT = txtSDT.getText();
        String dc = txtDiaChi.getText();
        if(ho_Ten.equals("") || cmnd.equals("")
                ||email.equals("")||soDT.equals("")||dc.equals("")){
            JOptionPane.showMessageDialog(null, "Hãy nhập đầy đủ thông tin","LỖI!!!",JOptionPane.ERROR_MESSAGE);
            check = false;
        }else {
        	if(kiemTraDL()) {
            	if(check = true){
                    kh_en.setHoTenKH(ho_Ten);
                    kh_en.setSoCMND(cmnd);
                    kh_en.setGioiTinh(gioiTinh);
                    kh_en.setNgaySinh(namSinh_input);
                    kh_en.setEmail(email);
                    kh_en.setSoDienThoai(soDT);
                    kh_en.setDiachi(dc);
                }
                try {
                    if(kh_md.themKhachHang(kh_en)){
                        JOptionPane.showMessageDialog(null,"Thêm thành công","THÀNH CÔNG",JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyKH.class.getName()).log(Level.SEVERE, null, ex);
                }
        	}
        }
        
    }//GEN-LAST:event_btnThemActionPerformed
	/**
	 * KIỂM TRA DỮ LIỆU.
	 * 
	 * @return
	 */
	public boolean kiemTraDL() {
		String sdt = txtSDT.getText().trim();
		String cmnd = txtSoCMND.getText().trim();
		String email = txtEmail.getText().trim();
		if (!(cmnd.length() > 0 && cmnd.matches("\\d{9}"))) {
			JOptionPane.showMessageDialog(null, "Lỗi : Nhập số Chứng minh nhân dân sai định dạng!!!\n Chứng minh nhân dân gồm 9 chữ số");
			return false;
		}
		// Số điện thoại gồm 10 chữ số
		if (!(sdt.length() > 0 && sdt.matches("\\d{10}"))) {
			JOptionPane.showMessageDialog(null, "Lỗi : Nhập số điện thoại sai định dạng!!!\n Điện thoại gồm 10 chữ số");
			return false;
		}
		String EMAIL_REGEX = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
	            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
		if (!(email.length() > 0 && email.matches(EMAIL_REGEX))) {
			JOptionPane.showMessageDialog(null, "Lỗi : Nhập địa chỉ email sai định dạng!!!\nĐịa chỉ Email theo mẫu sau: xxx@xxx.com");
			return false;
		}
		return true;
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemKH;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private javax.swing.JLabel lblDC;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSoCMND;
    private javax.swing.JLabel lblThemMoiKH;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoCMND;
    // End of variables declaration//GEN-END:variables
}
