 /*
 * Author: Nguyễn Đình Thông
 */
package Jpanel_Form_QuanLy;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import Connection.ConnectionDB;
import Entities.HangXe_entity;
import Entities.LoaiXe_entity;
import Entities.MauXe_entity;
import Entities.XeMay_entity;
import Jpanel_Form_NhanVien.QuanLyKH;
import Model.XeMay_model;


/**
 *
 * @author phanb
 */
public class QuanLyXeMay extends javax.swing.JPanel {
    /**
     * Creates new form QuanLyXeMay
     */
//	JButton btnThemXe,btnXoaXe, btnSuaXe, btnNhapLaiXe;
	//loại xe
    Vector data_loai = new Vector();
    ArrayList<LoaiXe_entity> ob_loai = new ArrayList<>();
    LoaiXe_entity lx_e = new LoaiXe_entity();
    //hãng xe
    Vector data = new Vector();
    ArrayList<HangXe_entity> ob_e = new ArrayList<>();
    XeMay_model ql_md = new XeMay_model();
    HangXe_entity hx_e = new HangXe_entity();
    DefaultTableModel md = new DefaultTableModel();
    //màu xe
    Vector data_mau = new Vector();
    ArrayList<MauXe_entity> ob_mau = new ArrayList<>();
    MauXe_entity mx_e = new MauXe_entity();
    // xe máy
    Vector data_xe = new Vector();
    ArrayList<XeMay_entity> ob_x = new ArrayList<>();
    XeMay_entity xm_e = new XeMay_entity();
    ArrayList<HangXe_entity> hxp = new ArrayList<>();
    ArrayList<LoaiXe_entity> lxp = new ArrayList<>();
    ArrayList<MauXe_entity> mxp = new ArrayList<>();
    String ImgPath;
    public QuanLyXeMay() {
        initComponents();
        getLoaiXe();
        getHang();
        getMau();
        getXeMay();
        getCombo_HangXe();
        getCombo_LoaiXe();
        getCombo_Mauxe();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlLoaiXe = new javax.swing.JPanel();
        lblMaLoai = new javax.swing.JLabel();
        txtMaLoai = new javax.swing.JTextField();
        lblTenLoai = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        btnThemLoai = new javax.swing.JButton();
        btnSuaLoai = new javax.swing.JButton();
        btnNhapLaiLoai = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblLoaiXe = new javax.swing.JTable();
        pnlHangXe = new javax.swing.JPanel();
        lblMaHang = new javax.swing.JLabel();
        txtMaHang = new javax.swing.JTextField();
        lblTenHang = new javax.swing.JLabel();
        txtTenHang = new javax.swing.JTextField();
        btnThemHang = new javax.swing.JButton();
        btnSuaHang = new javax.swing.JButton();
        btnNhapLaiHang = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblHangXe = new javax.swing.JTable();
        pnlMauXe = new javax.swing.JPanel();
        lblMaMau = new javax.swing.JLabel();
        txtMaMau = new javax.swing.JTextField();
        lblTenMau = new javax.swing.JLabel();
        txtTenMau = new javax.swing.JTextField();
        btnThemMau = new javax.swing.JButton();
        btnSuaMau = new javax.swing.JButton();
        btnNhapLaiMau = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMauXe = new javax.swing.JTable();
        pnlXeMay = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMaXe = new javax.swing.JLabel();
        txtMaXe = new javax.swing.JTextField();
        lblTenXe = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        lblHangXe = new javax.swing.JLabel();
        cmbHangXe = new javax.swing.JComboBox();
        lblLoaiXe = new javax.swing.JLabel();
        cmbLoaiXe = new javax.swing.JComboBox();
        lblMauXe = new javax.swing.JLabel();
        cmbMauXe = new javax.swing.JComboBox();
        lblSoMay = new javax.swing.JLabel();
        lblTitleAnh = new javax.swing.JLabel();
        lblAnhXe = new javax.swing.JLabel();
        txtSoMay = new javax.swing.JTextField();
        lblSoKhung = new javax.swing.JLabel();
        lblDungTich = new javax.swing.JLabel();
        lblGiaXe = new javax.swing.JLabel();
        txtSoKhung = new javax.swing.JTextField();
        txtDungTich = new javax.swing.JTextField();
        txtGiaXe = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblChonAnh = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXe = new javax.swing.JTable();
        btnThemXe = new javax.swing.JButton();
        btnSuaXe = new javax.swing.JButton();
        btnXoaXe = new javax.swing.JButton();
        btnNhapLaiXe = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1082, 667));

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1500));

        lblMaLoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMaLoai.setText("Mã loại xe");

        txtMaLoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblTenLoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTenLoai.setText("Tên loại xe");

        txtTenLoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N


        btnThemLoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Button-Add-icon.png"))); // NOI18N
        btnThemLoai.setText("Thêm loại xe");

        btnSuaLoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Actions-document-edit-icon.png"))); // NOI18N
        btnSuaLoai.setText("Sửa loại xe");


        btnNhapLaiLoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnNhapLaiLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit-clear.png"))); // NOI18N
        btnNhapLaiLoai.setText("Nhập lại");

        tblLoaiXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tblLoaiXe);

        javax.swing.GroupLayout pnlLoaiXeLayout = new javax.swing.GroupLayout(pnlLoaiXe);
        pnlLoaiXe.setLayout(pnlLoaiXeLayout);
        pnlLoaiXeLayout.setHorizontalGroup(
            pnlLoaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiXeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlLoaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoaiXeLayout.createSequentialGroup()
                        .addGroup(pnlLoaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlLoaiXeLayout.createSequentialGroup()
                                .addComponent(btnThemLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnSuaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLoaiXeLayout.createSequentialGroup()
                                .addComponent(lblMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(pnlLoaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoaiXeLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                               
                                .addGap(50, 50, 50)
                                .addComponent(btnNhapLaiLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoaiXeLayout.createSequentialGroup()
                                .addComponent(lblTenLoai)
                                .addGap(14, 14, 14)
                                .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        pnlLoaiXeLayout.setVerticalGroup(
            pnlLoaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiXeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlLoaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaLoai)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenLoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(pnlLoaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    
                    .addComponent(btnNhapLaiLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý loại xe", pnlLoaiXe);

        lblMaHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMaHang.setText("Mã hãng xe");

        txtMaHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblTenHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTenHang.setText("Tên hãng xe");

        txtTenHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnThemHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Button-Add-icon.png"))); // NOI18N
        btnThemHang.setText("Thêm hãng xe");

        btnSuaHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Actions-document-edit-icon.png"))); // NOI18N
        btnSuaHang.setText("Sửa hãng xe");


        btnNhapLaiHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnNhapLaiHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit-clear.png"))); // NOI18N
        btnNhapLaiHang.setText("Nhập lại");

        tblHangXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblHangXe);

        javax.swing.GroupLayout pnlHangXeLayout = new javax.swing.GroupLayout(pnlHangXe);
        pnlHangXe.setLayout(pnlHangXeLayout);
        pnlHangXeLayout.setHorizontalGroup(
            pnlHangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHangXeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlHangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHangXeLayout.createSequentialGroup()
                        .addGroup(pnlHangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlHangXeLayout.createSequentialGroup()
                                .addComponent(btnThemHang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnSuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHangXeLayout.createSequentialGroup()
                                .addComponent(lblMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(pnlHangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlHangXeLayout.createSequentialGroup()
                               
                                .addGap(50, 50, 50)
                                .addComponent(btnNhapLaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHangXeLayout.createSequentialGroup()
                                .addComponent(lblTenHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenHang))))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        pnlHangXeLayout.setVerticalGroup(
            pnlHangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHangXeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlHangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHang)
                    .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenHang)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(pnlHangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    
                    .addComponent(btnNhapLaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý hãng xe", pnlHangXe);

        lblMaMau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMaMau.setText("Mã màu xe");

        txtMaMau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblTenMau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTenMau.setText("Tên màu xe");

        txtTenMau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnThemMau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemMau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Button-Add-icon.png"))); // NOI18N
        btnThemMau.setText("Thêm màu xe");

        btnSuaMau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaMau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Actions-document-edit-icon.png"))); // NOI18N
        btnSuaMau.setText("Sửa màu xe");

        btnNhapLaiMau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnNhapLaiMau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit-clear.png"))); // NOI18N
        btnNhapLaiMau.setText("Nhập lại");

        tblMauXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblMauXe);

        javax.swing.GroupLayout pnlMauXeLayout = new javax.swing.GroupLayout(pnlMauXe);
        pnlMauXe.setLayout(pnlMauXeLayout);
        pnlMauXeLayout.setHorizontalGroup(
            pnlMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMauXeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMauXeLayout.createSequentialGroup()
                        .addGroup(pnlMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlMauXeLayout.createSequentialGroup()
                                .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnSuaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMauXeLayout.createSequentialGroup()
                                .addComponent(lblMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(pnlMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMauXeLayout.createSequentialGroup()
                               
                                .addGap(50, 50, 50)
                                .addComponent(btnNhapLaiMau, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMauXeLayout.createSequentialGroup()
                                .addComponent(lblTenMau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenMau))))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        pnlMauXeLayout.setVerticalGroup(
            pnlMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMauXeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaMau)
                    .addComponent(txtMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenMau)
                    .addComponent(txtTenMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(pnlMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                  
                    .addComponent(btnNhapLaiMau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý màu xe", pnlMauXe);

        pnlXeMay.setPreferredSize(new java.awt.Dimension(1239, 618));

        lblMaXe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaXe.setText("Mã xe");

        txtMaXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblTenXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTenXe.setText("Tên xe");

        txtTenXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblHangXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHangXe.setText("Hãng xe");

        cmbHangXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbHangXe.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        lblLoaiXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLoaiXe.setText("Loại xe");

        cmbLoaiXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbLoaiXe.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        lblMauXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMauXe.setText("Màu xe");

        cmbMauXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbMauXe.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        lblSoMay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSoMay.setText("Số máy");

        lblTitleAnh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTitleAnh.setText("Ảnh xe");

        txtSoMay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblSoKhung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSoKhung.setText("Số khung");

        lblDungTich.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDungTich.setText("Dung tích");

        lblGiaXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGiaXe.setText("Giá xe");

        txtSoKhung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtDungTich.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtGiaXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSoLuong.setText("Số lượng");

        txtSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblChonAnh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblChonAnh.setText("Ảnh Xe");

        btnChonAnh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnChonAnh.setText("Chọn đường dẫn ảnh");
      
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaXe)
                                    .addComponent(lblTenXe)
                                    .addComponent(lblHangXe))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTenXe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaXe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbHangXe, 0, 231, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSoMay)
                                    .addComponent(lblMauXe)
                                    .addComponent(lblLoaiXe))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMauXe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoMay)
                                    .addComponent(cmbLoaiXe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(73, 73, 73)
                        .addComponent(lblAnhXe, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSoKhung)
                                .addGap(29, 29, 29)
                                .addComponent(txtSoKhung))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoLuong)
                                    .addComponent(lblChonAnh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnChonAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(txtSoLuong)
                                    .addComponent(txtGiaXe)
                                    .addComponent(txtDungTich)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(lblTitleAnh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleAnh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAnhXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaXe)
                                    .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenXe)
                                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHangXe)
                                    .addComponent(cmbHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLoaiXe)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoKhung))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDungTich)
                                    .addComponent(txtDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGiaXe)
                                    .addComponent(txtGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSoLuong)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMauXe)
                                    .addComponent(cmbMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSoMay)
                                    .addComponent(txtSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblChonAnh)
                                    .addComponent(btnChonAnh))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        tblXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblXe);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 149, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
       
        
        
        javax.swing.GroupLayout pnlXeMayLayout = new javax.swing.GroupLayout(pnlXeMay);
        pnlXeMay.setLayout(pnlXeMayLayout);
        pnlXeMayLayout.setHorizontalGroup(
            pnlXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXeMayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlXeMayLayout.setVerticalGroup(
            pnlXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXeMayLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        //////////////
        btnThemXe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Button-Add-icon.png"))); // NOI18N
        btnThemXe.setText("Thêm xe");
        btnThemXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             //   btnThemXeActionPerformed(evt);
            }
        });

        btnSuaXe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Actions-document-edit-icon.png"))); // NOI18N
        btnSuaXe.setText("Sửa xe");
        btnSuaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             //   btnSuaXeActionPerformed(evt);
            }
        });

        btnXoaXe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXoaXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/btn_delete.png"))); // NOI18N
        btnXoaXe.setText("Xóa xe");
        btnXoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             //   btnXoaXeActionPerformed(evt);
            }
        });

        btnNhapLaiXe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnNhapLaiXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit-clear.png"))); // NOI18N
        btnNhapLaiXe.setText("Nhập lại");

        javax.swing.GroupLayout pnlXeMayLayout1 = new javax.swing.GroupLayout(pnlXeMay);
        pnlXeMay.setLayout(pnlXeMayLayout1);
        pnlXeMayLayout1.setHorizontalGroup(
            pnlXeMayLayout1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXeMayLayout1.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlXeMayLayout1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlXeMayLayout1.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnThemXe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSuaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnNhapLaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        pnlXeMayLayout1.setVerticalGroup(
            pnlXeMayLayout1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXeMayLayout1.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlXeMayLayout1.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapLaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );


        //////////////
        
        
        
        
        jTabbedPane1.addTab("Quản lý xe máy", pnlXeMay);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        
        // =================>>>>chức năng
        // Loại xe
        btnThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_loaiActionPerformed(evt);
            }
        });

        btnSuaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_loaiActionPerformed(evt);
            }
        });
        btnNhapLaiLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs_loaiActionPerformed(evt);
            }
        });
        tblLoaiXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiXeMouseClicked(evt);
            }
        });
        // Hãng xe
        btnThemHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_hangActionPerformed(evt);
            }
        });
        btnSuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_hangActionPerformed(evt);
            }
        });
        btnNhapLaiHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear();
            }
        });
        tblHangXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangMouseClicked(evt);
            }
        });
        
        // màu xe
        
        btnThemMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_mauActionPerformed(evt);
            }
        });
        btnSuaMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_mauActionPerformed(evt);
            }
        });
        btnNhapLaiMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMau();
            }
        });
        tblMauXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMauXeMouseClicked(evt);
            }
        });
        // xe may
        tblXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXeMayMouseClicked(evt);
            }
        });
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chon_fileActionPerformed(evt);
            }
        });
        btnThemXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_xeActionPerformed(evt);
            }
        });
        btnSuaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua_xeActionPerformed(evt);
            }
        });
        btnXoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa_xeActionPerformed(evt);
            }
        });
        btnNhapLaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_xeActionPerformed(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    
    
    // hàm 
    // ===============LOẠI XE=================================
    
    private void tblLoaiXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiXeMouseClicked
        txtMaLoai.setEditable(false);
        txtMaLoai.setForeground(Color.red);
        txtMaLoai.setBackground(new java.awt.Color(153, 153, 153));

        int row = tblLoaiXe.getSelectedRow();
        ob_loai = ql_md.getLoaiXe();

        txtMaLoai.setText(ob_loai.get(row).getMaLoaiXe());
        txtTenLoai.setText(ob_loai.get(row).getTenLoaiXe());
    }//GEN-LAST:event_tblLoaiXeMouseClicked
    
    public void getLoaiXe() {

        ob_loai = ql_md.getLoaiXe();

        Vector col_loai = new Vector();
        data_loai = new Vector();

        int i = 1;
        col_loai.addElement("STT");
        col_loai.addElement("Mã loại xe");
        col_loai.addElement("Tên loại xe");

        for (LoaiXe_entity ob : ob_loai) {
            Vector row_loai = new Vector();
            row_loai.add(i++);
            row_loai.add(ob.getMaLoaiXe());
            row_loai.add(ob.getTenLoaiXe());
            data_loai.add(row_loai);
        }

        md = new DefaultTableModel(data_loai, col_loai);
        tblLoaiXe.setModel(md);

    }
    private void add_loaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_loaiActionPerformed
        // TODO add your handling code here:
        Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String maloai = txtMaLoai.getText();
        String ten_loai_xe = txtTenLoai.getText();

        //kiểm tra xe đã tồn tại
        String check_loai = "SELECT * FROM LoaiXe Where tenLoaiXe='" + ten_loai_xe + "'";
        LoaiXe_entity loai = new LoaiXe_entity();
        if (ten_loai_xe.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn phải nhập thông tin xe", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            conn = ConnectionDB.openConnection();
            try {
                pst = conn.prepareCall(check_loai);
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Loại xe bạn thêm đã tồn tại", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                	lx_e.setMaLoaiXe(maloai);
                	lx_e.setTenLoaiXe(ten_loai_xe);
                    if (ql_md.add_loai_xe(lx_e)) {
                        JOptionPane.showMessageDialog(null, "Thêm loại xe thành công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        rs_loaiActionPerformed(evt);
                        getLoaiXe();
                    } else {
                        JOptionPane.showMessageDialog(null, "Lỗi thêm loại xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyXeMay.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_add_loaiActionPerformed

    private void rs_loaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs_loaiActionPerformed
        // TODO add your handling code here:
        txtMaLoai.setEditable(true);
        txtMaLoai.setForeground(Color.BLACK);
        txtMaLoai.setBackground(new java.awt.Color(255, 255, 255));
        txtMaLoai.setText(null);
        txtTenLoai.setText("");
    }//GEN-LAST:event_rs_loaiActionPerformed

    private void update_loaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_loaiActionPerformed
        // TODO add your handling code here:

        ob_loai = ql_md.getLoaiXe();
        boolean check = true;
        String ten = txtTenLoai.getText();

        int row = tblLoaiXe.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn loại xe cần cập nhật", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            LoaiXe_entity lx = new LoaiXe_entity();
            lx.setTenLoaiXe(ten);
            lx.setMaLoaiXe(ob_loai.get(row).getMaLoaiXe());
            if (ql_md.update_loai_xe(lx)) {
                JOptionPane.showMessageDialog(null, "Cập nhật loại xe thành công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                rs_loaiActionPerformed(evt);
                getLoaiXe();
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi cập nhật loại xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_update_loaiActionPerformed
                                          
    
    //========================HÃNG XE================================================
    public void clear() {
    	txtMaHang.setEditable(true);
    	txtMaHang.setForeground(Color.BLACK);
    	txtMaHang.setBackground(new java.awt.Color(255, 255, 255));
    	txtMaHang.setText(null);
        txtTenHang.setText(null);
    }
    private void add_hangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_hangActionPerformed
        // TODO add your handling code here:
        Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String ma = txtMaHang.getText();
        String ten = txtTenHang.getText();
        String check_hang = "SELECT HangXe.tenHang FROM HangXe WHERE tenHang='" + ten + "'";

        HangXe_entity hang = new HangXe_entity();
        hang.setMaHang(ma);
        hang.setTenHang(ten);
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn cần nhập thông tin hãng xe", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            conn = ConnectionDB.openConnection();
            try {
                pst = conn.prepareCall(check_hang);
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Tên hãng xe đã tồn tại", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else if (ql_md.add_hang(hang)) {
                    JOptionPane.showMessageDialog(null, "Thêm hãng xe thành công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clear();
                    getHang();
                } else {
                    JOptionPane.showMessageDialog(null, "Lỗi thêm hãng xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(QuanLyXeMay.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_add_hangActionPerformed

    private void update_hangActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        ob_e = ql_md.getHangXe();
        boolean check = true;
        String ten = txtTenHang.getText();

        int row = tblHangXe.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn hãng xe cần cập nhật", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            HangXe_entity hang = new HangXe_entity();
            hang.setTenHang(ten);
            hang.setMaHang(ob_e.get(row).getMaHang());
            if (ql_md.updateHangXe(hang)) {
                JOptionPane.showMessageDialog(null, "Cập nhật hãng xe thành công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                clear();
                getHang();
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi cập nhật hãng xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }                                           

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void cleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cleActionPerformed

    private void tblHangMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        txtMaHang.setEditable(false);
        txtMaHang.setForeground(Color.red);
        txtMaHang.setBackground(new java.awt.Color(153, 153, 153));
        int row = tblHangXe.getSelectedRow();
        ob_e = ql_md.getHangXe();

        txtMaHang.setText(ob_e.get(row).getMaHang());
        txtTenHang.setText(ob_e.get(row).getTenHang());


    }                                      
    
    public void getHang() {
        ob_e = ql_md.getHangXe();
        int i = 1;
        Vector col = new Vector();

        data = new Vector();
        col.add("STT");
        col.add("Mã hãng");
        col.add("Tên hãng");

        for (HangXe_entity lo : ob_e) {
            Vector row = new Vector();
            row.add(i++);
            row.add(lo.getMaHang());
            row.add(lo.getTenHang());
            data.add(row);

        }
        md = new DefaultTableModel(data, col);
        tblHangXe.setModel(md);

    }
    ///==================MÀU XE=====================================
    public void getMau() {
        ob_mau = ql_md.getMauXe();
        Vector col_mau = new Vector();
        int i = 1;
        col_mau.add("STT");
        col_mau.add("Mã màu xe");
        col_mau.add("Màu xe");
        data_mau = new Vector();
        for (MauXe_entity lk : ob_mau) {
            Vector row_mau = new Vector();
            row_mau.add(i++);
            row_mau.add(lk.getMaMau());
            row_mau.add(lk.getTenMau());
            data_mau.add(row_mau);
        }
        md = new DefaultTableModel(data_mau, col_mau);
        tblMauXe.setModel(md);

    }
    private void exit_loaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_loaiActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_loaiActionPerformed

    private void add_mauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_mauActionPerformed
        // TODO add your handling code here:
        Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String ten = txtTenMau.getText();

        //kiểm tra tồn tại màu xe
        String ma = txtMaMau.getText();
        String check_mau = "SELECT * FROM MauXe Where mauXe='" + ten + "'";

        if (ten.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn phải nhập thông tin màu xe", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            conn = ConnectionDB.openConnection();
            try {
                pst = conn.prepareCall(check_mau);
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Màu xe bạn nhập đã tồn tại", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    mx_e.setMaMau(ma);
                    mx_e.setTenMau(ten);
                    if (ql_md.add_mau_xe(mx_e)) {
                        JOptionPane.showMessageDialog(null, "Thêm màu xe thành công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        txtTenMau.setText(null);
                        getMau();
                    } else {
                        JOptionPane.showMessageDialog(null, "Lỗi thêm màu xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyXeMay.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_add_mauActionPerformed

    private void tblMauXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangXeMouseClicked
        // TODO add your handling code here:
        txtMaMau.setEditable(false);
        txtMaMau.setForeground(Color.red);
        txtMaMau.setBackground(new java.awt.Color(153, 153, 153));
        int row = tblMauXe.getSelectedRow();
        ob_mau = ql_md.getMauXe();
        txtMaMau.setText(ob_mau.get(row).getMaMau());
        txtTenMau.setText(ob_mau.get(row).getTenMau());

    }//GEN-LAST:event_tblHangXeMouseClicked

    public void clearMau() {
    	txtMaMau.setEditable(true);
    	txtMaMau.setForeground(Color.BLACK);
    	txtMaMau.setBackground(new java.awt.Color(255, 255, 255));
    	txtMaMau.setText(null);
        txtTenMau.setText(null);
    }
    private void update_mauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_hangActionPerformed
        // TODO add your handling code here:
        ob_mau = ql_md.getMauXe();
        boolean check = true;
        String ten = txtTenMau.getText();

        int row = tblMauXe.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn màu xe cần cập nhật", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            MauXe_entity hang = new MauXe_entity();
            hang.setTenMau(ten);
            hang.setMaMau(ob_mau.get(row).getMaMau());
            if (ql_md.updateMauXe(hang)) {
                JOptionPane.showMessageDialog(null, "Cập nhật màu xe thành công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                clearMau();
                getMau();
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi cập nhật màu xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_update_hangActionPerformed
    //======================> XE MÁY
    public void getXeMay() {
        ob_x = ql_md.getDL_xe();
        Vector col_xe = new Vector();
        data_xe = new Vector();

        int i = 1;
        col_xe.addElement("STT");
        col_xe.add("Mã xe");
        col_xe.addElement("Tên xe");
        col_xe.addElement("Số khung");
        col_xe.addElement("Số máy");
        col_xe.addElement("Hãng xe");
        col_xe.addElement("Loại xe");
        col_xe.addElement("Màu xe");
        col_xe.addElement("Dung tích");
        col_xe.addElement("Số lượng xe");
        col_xe.addElement("Giá xe");
        col_xe.addElement("Ảnh xe");
        NumberFormat fm = new DecimalFormat("#,###,###");
        for(XeMay_entity lo: ob_x) {
        	Vector row_xe = new Vector();
        	row_xe.add(i++);
        	row_xe.add(lo.getMaXe());
            row_xe.add(lo.getTenXe());
            row_xe.add(lo.getSoKhung());
            row_xe.add(lo.getSoMay());
            //haxng
            hxp = ql_md.hangxe_id(lo.getMa_Hang());
            row_xe.add(hxp.get(0).getTenHang());
            // loai
            lxp = ql_md.loaixe_id(lo.getMa_Loai());
            row_xe.add(lxp.get(0).getTenLoaiXe());
            // mau
            mxp = ql_md.mauxe_id(lo.getMa_Mau());
            row_xe.add(mxp.get(0).getTenMau());
            row_xe.add(lo.getDungTich());
            row_xe.add(lo.getSoLuongXe());
            row_xe.add(fm.format(lo.getGiaXe()));
            data_xe.add(row_xe);
        }
        md = new DefaultTableModel(data_xe, col_xe);
        tblXe.setModel(md);

    }
    
    public ImageIcon ResizeImage(String imagePath, byte[] bit) {
        ImageIcon myImg = null;
        if (imagePath != null) {
            myImg = new ImageIcon(imagePath);
        } else {
            myImg = new ImageIcon(bit);
        }
        Image img = myImg.getImage();
        Image newImg = img.getScaledInstance(lblAnhXe.getWidth(), lblAnhXe.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    private void chon_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chon_fileActionPerformed
        // TODO add your handling code here:
        JFileChooser choose_img = new JFileChooser();
        FileNameExtensionFilter loc_file = new FileNameExtensionFilter("png", "jpg", "jpeg");
        choose_img.setFileFilter(loc_file);
        //goi hien thi file
        int ht = choose_img.showOpenDialog(this);

        if (ht == JFileChooser.APPROVE_OPTION) {
            File file = choose_img.getSelectedFile();

            String path = file.getAbsolutePath();
            lblAnhXe.setIcon(ResizeImage(path, null));
            ImgPath = path;

        }
    }//GEN-LAST:event_chon_fileActionPerformed

    
    // đưa lên trển
    private void tblXeMayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXeMayMouseClicked
        // TODO add your handling code here:
        txtMaXe.setEditable(false);
        txtMaXe.setForeground(Color.red);
        txtMaXe.setBackground(new java.awt.Color(153, 153, 153));
        int row = tblXe.getSelectedRow();
        NumberFormat fm = new DecimalFormat("#,###,###");
        int sl = ob_x.get(row).getSoLuongXe();
        double gia = ob_x.get(row).getGiaXe();
        float dt = ob_x.get(row).getDungTich();
        String gia_st = String.valueOf(gia);
        String dtst = String.valueOf(dt);
        String slst = String.valueOf(sl);
        txtGiaXe.setText(fm.format(gia));
        txtDungTich.setText(dtst);
        ob_x = ql_md.getDL_xe();
        txtTenXe.setText(ob_x.get(row).getTenXe());
        txtMaXe.setText(ob_x.get(row).getMaXe());
        txtSoKhung.setText(ob_x.get(row).getSoKhung());
        txtSoMay.setText(ob_x.get(row).getSoMay());
        txtSoLuong.setText(slst);
        lblAnhXe.setIcon(ResizeImage(null, ob_x.get(row).getBit()));
        hxp = ql_md.hangxe_id(ob_x.get(row).getMa_Hang());
        cmbHangXe.setSelectedItem(hxp.get(0).getTenHang());

        mxp = ql_md.mauxe_id(ob_x.get(row).getMa_Mau());
        cmbMauXe.setSelectedItem(mxp.get(0).getTenMau());

        lxp = ql_md.loaixe_id(ob_x.get(row).getMa_Loai());
        cmbLoaiXe.setSelectedItem(lxp.get(0).getTenLoaiXe());
  
    }//GEN-LAST:event_tblXeMayMouseClicked
    public void getCombo_HangXe() {
       // ob_e = ql_md.getDL_xe();
        ob_e = ql_md.getHangXe();
    	for (HangXe_entity ob : ob_e) {
            cmbHangXe.addItem(ob.getTenHang());
        }
    }

    public void getCombo_LoaiXe() {
        ob_loai = ql_md.getLoaiXe();
        for (LoaiXe_entity ob : ob_loai) {
            cmbLoaiXe.addItem(ob.getTenLoaiXe());
        }
    }

    public void getCombo_Mauxe() {
        ob_mau = ql_md.getMauXe();
        for (MauXe_entity po : ob_mau) {
            cmbMauXe.addItem(po.getTenMau());
        }
    }
    // theem xe
    private void add_xeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_xeActionPerformed
        // TODO add your handling code here:
        ob_x = ql_md.getDL_xe();
        ob_loai = ql_md.getLoaiXe();
        ob_mau = ql_md.getMauXe();
        boolean check = true;
        Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String ma = txtMaXe.getText();
        String ten_xe = txtTenXe.getText();
        String gia_xe = txtGiaXe.getText();
        String soluong = txtSoLuong.getText();
        //hang
        int rowHang = cmbHangXe.getSelectedIndex();
        String idHang = ob_e.get(rowHang).getMaHang();

        //loai
        int loai = cmbLoaiXe.getSelectedIndex();
        String idLoai = ob_loai.get(loai).getMaLoaiXe();
        //mau
        int mau = cmbMauXe.getSelectedIndex();
        String idMau = ob_mau.get(mau).getMaMau();
        double gia = 0;
        float dt = 0;
        int sl=0;
        String sokhung = txtSoKhung.getText();
        String somay = txtSoMay.getText();
        String dungtich = txtDungTich.getText();

        //kiem tra xe da ton tai 
        String check_xe = "SELECT * FROM XeMay Where tenXe='" + ten_xe + "'";
        if (ten_xe.equals("") || gia_xe.equals("") || sokhung.equals("") || somay.equals("") || dungtich.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn cần nhập thông tin xe máy", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
        	if(kiemTraDL()) {
                try {
                    gia = Double.parseDouble(gia_xe);
                    check = true;
                } catch (Exception e) {
                    check = false;
                    JOptionPane.showMessageDialog(null, "Giá xe phải là số", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                try {
                	sl=Integer.parseInt(soluong);
                   check=true;
                } catch (Exception e) {
                    check=false;
                    JOptionPane.showMessageDialog(null, "Số lượng xe phải là số", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                try {
                	dt = Float.parseFloat(dungtich);
                	check=true;
                }catch(Exception e) {
                	check=false;
                    JOptionPane.showMessageDialog(null, "Dung tích xe phải là số", "ERROR", JOptionPane.ERROR_MESSAGE);

                }
                conn = ConnectionDB.openConnection();
                try {
                    pst = conn.prepareCall(check_xe);
                    rs = pst.executeQuery();
                    if (rs.next() && check == true) {
                        JOptionPane.showMessageDialog(null, "Tên xe đã tồn tại", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else if (check == true) {
                        InputStream img = new FileInputStream(new File(ImgPath));

                        XeMay_entity xm = new XeMay_entity();
                        xm.setMaXe(ma);
                        xm.setTenXe(ten_xe);
                        xm.setSoKhung(sokhung);
                        xm.setSoMay(somay);
                        xm.setMa_Hang(idHang);
                        xm.setMa_Loai(idLoai);
                        xm.setMa_Mau(idMau);
                        xm.setDungTich(dt);
                        xm.setSoLuongXe(sl);
                        xm.setGiaXe(gia);
                        xm.setAnhXe(img);
                        if (ql_md.add_xe_may(xm)) {
                            JOptionPane.showMessageDialog(null, "Thêm xe máy thành công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                            getXeMay();
                            reset_xeActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(null, "Lỗi thêm xe máy", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyXeMay.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(QuanLyXeMay.class.getName()).log(Level.SEVERE, null, ex);
                }
        	}


        }
    }//GEN-LAST:event_add_xeActionPerformed
    private void reset_xeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_xeActionPerformed
        // TODO add your handling code here:
        txtMaXe.setEditable(true);
        txtMaXe.setForeground(Color.BLACK);
        txtMaXe.setBackground(new java.awt.Color(255, 255, 255));
        txtTenXe.setText("");
        txtMaXe.setText(null);
        txtSoKhung.setText("");
        txtSoMay.setText("");
        txtGiaXe.setText("");
        txtDungTich.setText("");
        txtSoLuong.setText(null);
        lblAnhXe.setIcon(null);
    }//GEN-LAST:event_reset_xeActionPerformed
    
    private void sua_xeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua_xeActionPerformed
		// TODO add your handling code here:

		boolean check = true;
		ob_x = ql_md.getDL_xe();
		ob_loai = ql_md.getLoaiXe();
		ob_mau = ql_md.getMauXe();
		String ten_xe = txtTenXe.getText();
		String gia_xe = txtGiaXe.getText();
		String soluong = txtSoLuong.getText();
		String dungtich = txtDungTich.getText();
		// hang
		int rowHang = cmbHangXe.getSelectedIndex();
		String idHang = ob_e.get(rowHang).getMaHang();

		// loai
		int loai = cmbLoaiXe.getSelectedIndex();
		String idLoai = ob_loai.get(loai).getMaLoaiXe();
		// mau
		int mau = cmbMauXe.getSelectedIndex();
		String idMau = ob_mau.get(mau).getMaMau();
		double gia = 0;
		float dt = 0;
		int sl = 0;
		String sokhung = txtSoKhung.getText();
		String somay = txtSoMay.getText();

		int row = tblXe.getSelectedRow();

		if (row == -1) {
			JOptionPane.showMessageDialog(null, "Bạn cần chọn xe máy cần sửa", "ERROR", JOptionPane.ERROR_MESSAGE);
			check = false;
		} else if (check == true) {
			if(kiemTraDL()) {
				try {
					gia = Double.parseDouble(gia_xe);
					check = true;
				} catch (Exception e) {
					check = false;
					JOptionPane.showMessageDialog(null, "Giá xe phải là số", "ERROR", JOptionPane.ERROR_MESSAGE);
				}
				try {
					sl = Integer.parseInt(soluong);
					check = true;
				} catch (Exception e) {
					check = false;
					JOptionPane.showMessageDialog(null, "Số lượng xe phải là số", "ERROR", JOptionPane.ERROR_MESSAGE);
				}
				try {
					dt = Float.parseFloat(dungtich);
					check = true;
				} catch (Exception e) {
					check = false;
					JOptionPane.showMessageDialog(null, "Dung tích xe phải là số", "ERROR", JOptionPane.ERROR_MESSAGE);

				}

				if (ImgPath == null) {
					XeMay_entity xm = new XeMay_entity();
					xm.setTenXe(ten_xe);
					xm.setSoKhung(sokhung);
					xm.setSoMay(somay);
					xm.setMa_Hang(idHang);
					xm.setMa_Loai(idLoai);
					xm.setMa_Mau(idMau);
					xm.setDungTich(dt);
					xm.setSoLuongXe(sl);
					xm.setGiaXe(gia);
					xm.setMaXe(ob_x.get(row).getMaXe());

					if (ql_md.update_xe(xm)) {
						JOptionPane.showMessageDialog(null, "Sửa thông tin xe máy thành công", "Thông báo",
								JOptionPane.INFORMATION_MESSAGE);
						getXeMay();
						reset_xeActionPerformed(evt);
					} else {
						JOptionPane.showMessageDialog(null, "Lỗi sửa thông tin xe máy", "ERROR", JOptionPane.ERROR_MESSAGE);
					}

				} else {
					XeMay_entity xm = new XeMay_entity();
					try {
						InputStream img = new FileInputStream(ImgPath);
						xm.setTenXe(ten_xe);
						xm.setSoKhung(sokhung);
						xm.setSoMay(somay);
						xm.setMa_Hang(idHang);
						xm.setMa_Loai(idLoai);
						xm.setMa_Mau(idMau);
						xm.setDungTich(dt);
						xm.setSoLuongXe(sl);
						xm.setGiaXe(gia);
						xm.setAnhXe(img);
						xm.setMaXe(ob_x.get(row).getMaXe());

					} catch (FileNotFoundException ex) {
						Logger.getLogger(QuanLyXeMay.class.getName()).log(Level.SEVERE, null, ex);
					}

					if (ql_md.update_anh_xe(xm)) {
						JOptionPane.showMessageDialog(null, "Sửa thông tin xe máy thành công", "Thông báo",
								JOptionPane.INFORMATION_MESSAGE);
						getXeMay();
						reset_xeActionPerformed(evt);
					} else {
						JOptionPane.showMessageDialog(null, "Lỗi sửa thông tin xe máy", "ERROR", JOptionPane.ERROR_MESSAGE);
					}
				}
			}



		}
    }//GEN-LAST:event_sua_xeActionPerformed

    private void xoa_xeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa_xeActionPerformed
		// TODO add your handling code here:
		ob_x = ql_md.getDL_xe();
		int row = tblXe.getSelectedRow();
		boolean check = true;
		if (row == -1) {
			JOptionPane.showMessageDialog(null, "Bạn chọn xe máy muốn xóa", "ERROR", JOptionPane.ERROR_MESSAGE);
			check = false;
		} else if (check == true) {
			int click = JOptionPane.showConfirmDialog(null, "Bạn có chắn chắn muốn xóa", "Thông báo",
					JOptionPane.YES_NO_OPTION);
			if (click == JOptionPane.YES_OPTION) {

				if (ql_md.Dis_xe_may(ob_x.get(row).getMaXe())) {
					JOptionPane.showMessageDialog(null, "Xóa xe thành công", "SUCCESS",
							JOptionPane.INFORMATION_MESSAGE);
					getXeMay();
					reset_xeActionPerformed(evt);
				} else {
					JOptionPane.showMessageDialog(null, "Lỗi xóa xe máy", "ERROR", JOptionPane.ERROR_MESSAGE);
				}
			}

		}

    }//GEN-LAST:event_xoa_xeActionPerformed
	/**
	 * KIỂM TRA DỮ LIỆU.
	 * 
	 * @return
	 */
	public boolean kiemTraDL() {
		String khung = txtSoKhung.getText().trim();
		String may = txtSoMay.getText().trim();
		String dt = txtDungTich.getText().trim();
		String sk = "^.*(?=.{7})(?=..*[0-9])(?=.*[A-Z]).*$";
		if (!(khung.length() > 0 && khung.matches(sk))) {
			JOptionPane.showMessageDialog(null,
					"Lỗi : Nhập Số khung sai định dạng!!!\n Số khung bao gồm 7 kí tự cả kí tự số và chữ in hoa.");
			return false;
		}
		String sm = "^.*(?=.{11})(?=..*[0-9])(?=.*[A-Z]).*$";
		if (!(may.length() > 0 && may.matches(sm))) {
			JOptionPane.showMessageDialog(null, "Lỗi : Nhập Số máy sai định dạng!!!\n Số máy bao gồm 11 kí tự cả kí tự số và chữ in hoa.");
			return false;
		}

		
		return true;
	}
	public void kiemTraDLSO() {
		String dt = txtDungTich.getText().trim();
		float dtich = Float.parseFloat(dt);
		String gia = txtGiaXe.getText().trim();
		float giaxe = Float.parseFloat(gia);
		String sl = txtSoLuong.getText().trim();
		int solg = Integer.parseInt(sl);
		if (dtich<=0) {
			JOptionPane.showMessageDialog(null,"Lỗi : Dung tích xe phải lớn hơn 0.");
		}
		if (giaxe<=0) {
			JOptionPane.showMessageDialog(null,"Lỗi : Giá xe phải lớn hơn 0.");
		}
		if (solg<=0) {
			JOptionPane.showMessageDialog(null,"Lỗi : Số lượng xe phải lớn hơn 0.");
		}		

	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnNhapLaiLoai;
    private javax.swing.JButton btnNhapLaiMau;
    private javax.swing.JButton btnNhapLaiHang;
    private javax.swing.JButton btnSuaLoai;
    private javax.swing.JButton btnSuaMau;
    private javax.swing.JButton btnSuaHang;
    private javax.swing.JButton btnThemLoai;
    private javax.swing.JButton btnThemMau;
    private javax.swing.JButton btnThemHang;
    private javax.swing.JButton btnSuaXe;
    private javax.swing.JButton btnThemXe;
    private javax.swing.JButton btnXoaXe;
    private javax.swing.JButton btnNhapLaiXe;
    private javax.swing.JComboBox cmbHangXe;
    private javax.swing.JComboBox cmbLoaiXe;
    private javax.swing.JComboBox cmbMauXe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblXe;
    private javax.swing.JLabel lblAnhXe;
    private javax.swing.JLabel lblChonAnh;
    private javax.swing.JLabel lblDungTich;
    private javax.swing.JLabel lblGiaXe;
    private javax.swing.JLabel lblHangXe;
    private javax.swing.JLabel lblLoaiXe;
    private javax.swing.JLabel lblMaLoai;
    private javax.swing.JLabel lblMaMau;
    private javax.swing.JLabel lblMaHang;
    private javax.swing.JLabel lblMaXe;
    private javax.swing.JLabel lblMauXe;
    private javax.swing.JLabel lblSoKhung;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblSoMay;
    private javax.swing.JLabel lblTenLoai;
    private javax.swing.JLabel lblTenMau;
    private javax.swing.JLabel lblTenHang;
    private javax.swing.JLabel lblTenXe;
    private javax.swing.JLabel lblTitleAnh;
    private javax.swing.JPanel pnlHangXe;
    private javax.swing.JPanel pnlLoaiXe;
    private javax.swing.JPanel pnlMauXe;
    private javax.swing.JPanel pnlXeMay;
    private javax.swing.JTable tblHangXe;
    private javax.swing.JTable tblMauXe;
    private javax.swing.JTable tblLoaiXe;
    private javax.swing.JTextField txtDungTich;
    private javax.swing.JTextField txtGiaXe;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtMaMau;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtSoKhung;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoMay;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txtTenMau;
    private javax.swing.JTextField txtTenHang;
    private javax.swing.JTextField txtTenXe;
    // End of variables declaration//GEN-END:variables
}


// sửa xe: phải sửa giá, không sửa giá nó báo lỗi và đưa giá xe =0;
