/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jpanel_Form_QuanLy;

import Entities.HoaDon_entity;
import Entities.KhachHang_entity;
import Entities.XeMay_entity;
import Model.HoaDon_model;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author phanb
 */
public class ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThongKe = new javax.swing.JLabel();
        btnDanhSachXe = new javax.swing.JButton();
        btnXeBanChay = new javax.swing.JButton();
        btnXeCon = new javax.swing.JButton();

        lblThongKe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(204, 0, 51));
        lblThongKe.setText("THỐNG KÊ");

        btnDanhSachXe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDanhSachXe.setText("Danh Sách xe đã bán");
        btnDanhSachXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachXeActionPerformed(evt);
            }
        });

        btnXeBanChay.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXeBanChay.setText("Top xe bán chạy nhất");
        btnXeBanChay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXeBanChayActionPerformed(evt);
            }
        });

        btnXeCon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXeCon.setText("Xe còn trong kho");
        btnXeCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXeConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(509, 509, 509)
                .addComponent(lblThongKe)
                .addContainerGap(540, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXeCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDanhSachXe, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXeBanChay, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblThongKe)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDanhSachXe, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXeBanChay, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(btnXeCon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDanhSachXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachXeActionPerformed
        // TODO add your handling code here:
        ArrayList<HoaDon_entity> ob_in=new ArrayList<>();
        Connection conn;
        HoaDon_model hd_md=new HoaDon_model();
        ob_in=hd_md.ban_xe();
        ArrayList<KhachHang_entity> ob_kh = new ArrayList<>();
        ArrayList<XeMay_entity> ob_id_xe = new ArrayList<>();
        List<Map<String, ?>> datax=new ArrayList<>();
        for (HoaDon_entity ob : ob_in) {
            Map<String,Object> row_x=new HashMap<String,Object>();
            ob_kh = hd_md.getIDkhachhang(ob.getMaKH());
            row_x.put("ChiTietHoaDon_maHD",ob.getMaHoaDon());
            row_x.put("HoaDon_maKH",ob_kh.get(0).getHoTenKH());
            //row_x.put("diaChi",ob_kh.get(0).getDiachi());
            //row_x.put("soDienThoai",ob_kh.get(0).getSoDienThoai());
            ob_id_xe = hd_md.getIDxe(ob.getMaXe());
            row_x.put("ChiTietHoaDon_maXe",ob_id_xe.get(0).getTenXe());
            row_x.put("ChiTietHoaDon_donGia",ob.getDonGia());
            row_x.put("ChiTietHoaDon_soLuong",ob.getSoLuong());
            row_x.put("ChiTietHoaDon_thanhTien",ob.getThanhTien());
            //row_x.put("HoaDon_ngayLap", ob.getNgayLapHoaDon());
            //row_x.put("thueXe", ob.getThueXe());
            //row_x.put("tongTien",ob.getTongTien());
            datax.add(row_x);
        }
        JRDataSource jrsource=new JRBeanCollectionDataSource(datax);
        String sourceName="src\\Ireport\\DanhSachXeBan.jrxml";
        try {
            JasperReport rp=JasperCompileManager.compileReport(sourceName);
            JasperPrint filledReport=JasperFillManager.fillReport(rp, null,jrsource);
            JasperViewer jw=new JasperViewer(filledReport);
            jw.setVisible(true);
            jw.setDefaultCloseOperation(JasperViewer.DISPOSE_ON_CLOSE);

        } catch (JRException ex) {
            Logger.getLogger(ThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDanhSachXeActionPerformed

    private void btnXeBanChayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXeBanChayActionPerformed
        // TODO add your handling code here:
        HoaDon_model hd_md=new HoaDon_model();
        ArrayList<HoaDon_entity> ob_ban=new ArrayList<>();
        ArrayList<XeMay_entity> xe_may=new ArrayList<>();
        ob_ban=hd_md.xe_ban_chay_nhat();
        ArrayList<XeMay_entity> ob_id_xe = new ArrayList<>();
        List<Map<String, ?>> datax=new ArrayList<>();
        for (HoaDon_entity ob : ob_ban) {
            Map<String,Object> row_x=new HashMap<String,Object>();
            row_x.put("ChiTietHoaDon_maXe",ob.getMaXe());
            xe_may=hd_md.getIDxe(ob.getMaXe());
            row_x.put("XeMay_tenXe",xe_may.get(0).getTenXe());
            row_x.put("ChiTietHoaDon_donGia",ob.getDonGia());
            row_x.put("TONG",ob.getBanChay());
            datax.add(row_x);
        }
        JRDataSource jrsource=new JRBeanCollectionDataSource(datax);
        String sourceName="src\\Ireport\\XeBanChay.jrxml";
        try {
            JasperReport rp=JasperCompileManager.compileReport(sourceName);
            JasperPrint filledReport=JasperFillManager.fillReport(rp, null,jrsource);
            JasperViewer jw=new JasperViewer(filledReport);
            jw.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(HoaDon_model.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXeBanChayActionPerformed

    private void btnXeConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXeConActionPerformed
        // TODO add your handling code here:
        ArrayList<XeMay_entity> ob_in=new ArrayList<>();
        Connection conn;
        HoaDon_model hd_md=new HoaDon_model();
        ob_in=hd_md.xe_con_trong_kho();
        ArrayList<XeMay_entity> ob_id_xe = new ArrayList<>();
        List<Map<String, ?>> datax=new ArrayList<>();
        for (XeMay_entity ob : ob_in) {
            Map<String,Object> row_x=new HashMap<String,Object>();
            row_x.put("XeMay_maXe",ob.getMaXe());
            ob_id_xe = hd_md.getIDxe(ob.getMaXe());
            row_x.put("XeMay_tenXe",ob_id_xe.get(0).getTenXe());
            row_x.put("XeMay_maMauXe",ob.getMauXe());
            row_x.put("XeMay_soLuongXe",ob.getSoLuongXe());
            row_x.put("XeMay_giaXe",ob.getGiaXe());
            datax.add(row_x);
        }
        JRDataSource jrsource=new JRBeanCollectionDataSource(datax);
        String sourceName="src\\Ireport\\XeTonKho.jrxml";
        try {
            JasperReport rp=JasperCompileManager.compileReport(sourceName);
            JasperPrint filledReport=JasperFillManager.fillReport(rp, null,jrsource);
            JasperViewer jw=new JasperViewer(filledReport);
            jw.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(ThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXeConActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSachXe;
    private javax.swing.JButton btnXeBanChay;
    private javax.swing.JButton btnXeCon;
    private javax.swing.JLabel lblThongKe;
    // End of variables declaration//GEN-END:variables
}
