///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package Jpanel_Form_QuanLy;
//
///**
// *
// * @author Win 10
// */
//public class Xe extends javax.swing.JPanel {
//
//    /**
//     * Creates new form Xe
//     */
//    public Xe() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        pnlThongTin = new javax.swing.JPanel();
//        lblMaXe = new javax.swing.JLabel();
//        txtTenXe = new javax.swing.JTextField();
//        lblTenXe = new javax.swing.JLabel();
//        txtMaXe = new javax.swing.JTextField();
//        lblSoKhung = new javax.swing.JLabel();
//        txtSoKhung = new javax.swing.JTextField();
//        lblSoMay = new javax.swing.JLabel();
//        txtSoMay = new javax.swing.JTextField();
//        lblHangXe = new javax.swing.JLabel();
//        lblDungTich = new javax.swing.JLabel();
//        lblMauXe = new javax.swing.JLabel();
//        lblGiaXe = new javax.swing.JLabel();
//        lblLoaiXe = new javax.swing.JLabel();
//        txtDungTich = new javax.swing.JTextField();
//        lblDVDungTich = new javax.swing.JLabel();
//        txtHangXe = new javax.swing.JTextField();
//        cbbLoaiXe = new javax.swing.JComboBox<>();
//        cbbMauXe = new javax.swing.JComboBox<>();
//        txtGiaXe = new javax.swing.JTextField();
//        lblDVGiaXe = new javax.swing.JLabel();
//        lblAnhXe = new javax.swing.JLabel();
//        btnAnhXe = new javax.swing.JButton();
//        lblAnh = new javax.swing.JLabel();
//        pnlChucNang = new javax.swing.JPanel();
//        btnXoa = new javax.swing.JButton();
//        btnThem = new javax.swing.JButton();
//        btnCapNhat = new javax.swing.JButton();
//        btnXoaTrang = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        tblXeMay = new javax.swing.JTable();
//
//        pnlThongTin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        lblMaXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblMaXe.setText("Mã xe");
//
//        lblTenXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblTenXe.setText("Tên xe");
//
//        lblSoKhung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblSoKhung.setText("Số khung");
//
//        lblSoMay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblSoMay.setText("Số máy ");
//
//        lblHangXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblHangXe.setText("Hãng xe");
//
//        lblDungTich.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblDungTich.setText("Dung tích");
//
//        lblMauXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblMauXe.setText("Màu xe");
//
//        lblGiaXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblGiaXe.setText("Giá xe");
//
//        lblLoaiXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblLoaiXe.setText("Loại xe");
//
//        txtDungTich.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtDungTichActionPerformed(evt);
//            }
//        });
//
//        lblDVDungTich.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lblDVDungTich.setText("CC");
//
//        cbbLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tay ga", "Tay côn" }));
//
//        cbbMauXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xanh", "Đỏ", "Đỏ-Đen", "Trắng", "Đen" }));
//
//        lblDVGiaXe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lblDVGiaXe.setText("VND");
//
//        lblAnhXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
//        lblAnhXe.setText("Ảnh xe");
//
//        btnAnhXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Button-Add-icon.png"))); // NOI18N
//        btnAnhXe.setText("Thêm ảnh xe");
//        btnAnhXe.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnAnhXeActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
//        pnlThongTin.setLayout(pnlThongTinLayout);
//        pnlThongTinLayout.setHorizontalGroup(
//            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(pnlThongTinLayout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(pnlThongTinLayout.createSequentialGroup()
//                        .addComponent(lblMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
//                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                                .addComponent(lblSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addComponent(lblTenXe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addComponent(lblSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(lblDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(pnlThongTinLayout.createSequentialGroup()
//                                .addGap(4, 4, 4)
//                                .addComponent(txtDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(8, 8, 8)
//                                .addComponent(lblDVDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addComponent(txtSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                .addGap(18, 18, 18)
//                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(pnlThongTinLayout.createSequentialGroup()
//                        .addComponent(lblHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(txtHangXe))
//                    .addGroup(pnlThongTinLayout.createSequentialGroup()
//                        .addComponent(lblLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(cbbLoaiXe, 0, 159, Short.MAX_VALUE))
//                    .addGroup(pnlThongTinLayout.createSequentialGroup()
//                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                            .addComponent(lblAnhXe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
//                            .addComponent(lblGiaXe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(btnAnhXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                            .addGroup(pnlThongTinLayout.createSequentialGroup()
//                                .addComponent(txtGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(lblDVGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(0, 0, Short.MAX_VALUE))))
//                    .addGroup(pnlThongTinLayout.createSequentialGroup()
//                        .addComponent(lblMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(cbbMauXe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                .addContainerGap())
//        );
//        pnlThongTinLayout.setVerticalGroup(
//            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(pnlThongTinLayout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(pnlThongTinLayout.createSequentialGroup()
//                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                            .addGroup(pnlThongTinLayout.createSequentialGroup()
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addComponent(lblHangXe)
//                                    .addComponent(txtHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(lblLoaiXe)
//                                    .addComponent(cbbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(lblMauXe)
//                                    .addComponent(cbbMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                            .addGroup(pnlThongTinLayout.createSequentialGroup()
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(lblMaXe)
//                                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(lblTenXe)
//                                    .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(lblSoKhung)
//                                    .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                        .addGap(0, 37, Short.MAX_VALUE)
//                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(lblGiaXe)
//                                    .addComponent(txtGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(lblDVGiaXe))
//                                .addGap(18, 18, 18)
//                                .addComponent(lblAnhXe))
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(lblSoMay)
//                                    .addComponent(txtSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(lblDungTich)
//                                    .addComponent(txtDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(lblDVDungTich)))
//                            .addComponent(btnAnhXe, javax.swing.GroupLayout.Alignment.TRAILING)))
//                    .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addGap(16, 16, 16))
//        );
//
//        pnlChucNang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/btn_delete.png"))); // NOI18N
//        btnXoa.setText("Xóa");
//
//        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/btn_add.png"))); // NOI18N
//        btnThem.setText("Thêm");
//
//        btnCapNhat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Actions-document-edit-icon.png"))); // NOI18N
//        btnCapNhat.setText("Cập nhật");
//
//        btnXoaTrang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit-clear.png"))); // NOI18N
//        btnXoaTrang.setText("Xóa trắng");
//
//        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
//        pnlChucNang.setLayout(pnlChucNangLayout);
//        pnlChucNangLayout.setHorizontalGroup(
//            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChucNangLayout.createSequentialGroup()
//                .addGap(20, 20, 20)
//                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
//                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
//                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addGap(27, 27, 27))
//        );
//        pnlChucNangLayout.setVerticalGroup(
//            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChucNangLayout.createSequentialGroup()
//                .addGap(32, 32, 32)
//                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(44, 44, 44))
//        );
//
//        tblXeMay.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null, null, null}
//            },
//            new String [] {
//                "Mã xe", "Tên xe", "Số khung", "Số máy", "Dung tích", "Hãng xe", "Loại xe", "Màu xe", "Giá xe", "Ảnh xe"
//            }
//        ));
//        jScrollPane1.setViewportView(tblXeMay);
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(jScrollPane1)
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addComponent(pnlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addComponent(pnlChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                .addContainerGap())
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(pnlChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        this.setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 1055, Short.MAX_VALUE)
//            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(layout.createSequentialGroup()
//                    .addGap(0, 0, Short.MAX_VALUE)
//                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addGap(0, 0, Short.MAX_VALUE)))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 692, Short.MAX_VALUE)
//            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(layout.createSequentialGroup()
//                    .addGap(0, 0, Short.MAX_VALUE)
//                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addGap(0, 0, Short.MAX_VALUE)))
//        );
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void txtDungTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDungTichActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtDungTichActionPerformed
//
//    private void btnAnhXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhXeActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_btnAnhXeActionPerformed
//
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton btnAnhXe;
//    private javax.swing.JButton btnCapNhat;
//    private javax.swing.JButton btnThem;
//    private javax.swing.JButton btnXoa;
//    private javax.swing.JButton btnXoaTrang;
//    private javax.swing.JComboBox<String> cbbLoaiXe;
//    private javax.swing.JComboBox<String> cbbMauXe;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JLabel lblAnh;
//    private javax.swing.JLabel lblAnhXe;
//    private javax.swing.JLabel lblDVDungTich;
//    private javax.swing.JLabel lblDVGiaXe;
//    private javax.swing.JLabel lblDungTich;
//    private javax.swing.JLabel lblGiaXe;
//    private javax.swing.JLabel lblHangXe;
//    private javax.swing.JLabel lblLoaiXe;
//    private javax.swing.JLabel lblMaXe;
//    private javax.swing.JLabel lblMauXe;
//    private javax.swing.JLabel lblSoKhung;
//    private javax.swing.JLabel lblSoMay;
//    private javax.swing.JLabel lblTenXe;
//    private javax.swing.JPanel pnlChucNang;
//    private javax.swing.JPanel pnlThongTin;
//    private javax.swing.JTable tblXeMay;
//    private javax.swing.JTextField txtDungTich;
//    private javax.swing.JTextField txtGiaXe;
//    private javax.swing.JTextField txtHangXe;
//    private javax.swing.JTextField txtMaXe;
//    private javax.swing.JTextField txtSoKhung;
//    private javax.swing.JTextField txtSoMay;
//    private javax.swing.JTextField txtTenXe;
//    // End of variables declaration//GEN-END:variables
//}
