  /*
 * Author: Phan Xuân Bách
 */
package GUI_Form;

import Connection.ConnectionDB;
import Entities.NhanVien_entity;
import Model.DangNhap_model;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author phanb
 */
public class DangNhap extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement st = null;
    public static ResultSet rs = null;
    public static PreparedStatement pst = null;
    DangNhap_model lg_md = new DangNhap_model();
    public static String ten_ad;
    public static String id_user;
    public static String pass_id;
    public static String maNV;

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        conn = ConnectionDB.openConnection();
        getRootPane().setDefaultButton(btnDangNhap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDangNhap = new javax.swing.JLabel();
        lblTenTK = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        lblMK = new javax.swing.JLabel();
        txtMK = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        cmbChucVu = new javax.swing.JComboBox();
        btnDangNhap = new javax.swing.JButton();
        lblHinh = new javax.swing.JLabel();
        lblHinh1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblDangNhap.setText("Đăng nhập");

        lblTenTK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTenTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Preppy-icon.png"))); // NOI18N
        lblTenTK.setText("Tài khoản");

        txtTenTK.setText("Admin");
        txtTenTK.setToolTipText("Nhập tài khoản của bạn");

        lblMK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/modify-key-icon.png"))); // NOI18N
        lblMK.setText("Mật khẩu");

        txtMK.setText("@Tt12345");
        txtMK.setToolTipText("Nhập mật khẩu của bạn");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/User-Group-icon.png"))); // NOI18N
        jLabel1.setText("Chức vụ");

        cmbChucVu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhân viên bán hàng", "Quản lý" }));

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8-login-rounded-50.png"))); // NOI18N
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblDangNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTenTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenTK)
                            .addComponent(txtMK, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbChucVu, 0, 233, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDangNhap)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMK, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ảnh xe/Vario2019.jpg"))); // NOI18N

        lblHinh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ảnh xe/Winner.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHinh)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblHinh1)
                        .addGap(18, 18, 18)
                        .addComponent(lblHinh)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        String ten = txtTenTK.getText();
        String passs = txtMK.getText();
        if (ten.isEmpty() || passs.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập thông tin tài khoản và mật khẩu",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        } else {
            rs = DangNhap_model.loginData(ten, passs);
            try {
                if (rs.next()) {
                    NhanVien_entity nv = new NhanVien_entity();

                    nv.setMaNV(rs.getString("maNV"));

                    nv.setMatKhau(rs.getString("matKhau"));
                    nv.setTaiKhoan(rs.getString("taiKhoan"));
                    nv.setHoTen(rs.getString("hoTen"));
                    id_user = nv.getMaNV();
                    ten_ad = nv.getTaiKhoan();
                    pass_id = nv.getMatKhau();
                    maNV = nv.getMaNV();
                    JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công", "SUCCESS",
                            JOptionPane.INFORMATION_MESSAGE);
                    if(cmbChucVu.getSelectedItem().toString().equalsIgnoreCase("quản lý")){
                        TrangChuQuanLy ql = new TrangChuQuanLy();
                        ql.setVisible(true);
                        this.setVisible(false);
                    }
                    if(cmbChucVu.getSelectedItem().toString().equalsIgnoreCase("Nhân viên bán hàng")){
                        TrangChuNhanVien nvien = new TrangChuNhanVien();
                        nvien.setVisible(true);
                        this.setVisible(false);
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Tên tài khoản hoặc mật khẩu không đúng",
                            "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
//        if (cmbChucVu.getSelectedItem().toString().equalsIgnoreCase("Quản lý")) {
//            TrangChuQuanLy ql = new TrangChuQuanLy();
//            ql.setVisible(true);
//            this.setVisible(false);
//        } else {
//            TrangChuNhanVien nv = new TrangChuNhanVien();
//            nv.setVisible(true);
//            this.setVisible(false);
//        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JComboBox cmbChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblHinh1;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblTenTK;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
