/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Form;

import Connection.ConnectionDB;
import Entities.NhanVien_entity;
import static GUI_Form.DangNhap.rs;
import Model.DangNhap_model;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author phanb
 */
public class DoiMatKhau extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement stmt;
    ResultSet rs;
    DangNhap dn = new DangNhap();
    DangNhap_model dn_md = new DangNhap_model();
    
    public DoiMatKhau() {
        initComponents();
        txtTK.setText(DangNhap.ten_ad);
        try {
            conn = ConnectionDB.openConnection();
        } catch (Exception e) {
        }
        getRootPane().setDefaultButton(btnDoi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblMKCu = new javax.swing.JLabel();
        lblMKMoi = new javax.swing.JLabel();
        lblXNMK = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        txtMKCu = new javax.swing.JPasswordField();
        txtMKMoi = new javax.swing.JPasswordField();
        txtXNMK = new javax.swing.JPasswordField();
        btnDoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 0, 0));
        lblTitle.setText("ĐỔI MẬT KHẨU");

        lblTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTaiKhoan.setText("Tài khoản");

        lblMKCu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMKCu.setText("Nhập mật khẩu cũ");

        lblMKMoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMKMoi.setText("Nhập mật khẩu mới");

        lblXNMK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblXNMK.setText("Nhập lại mật khẩu mới");

        txtTK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMKCu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMKMoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtXNMK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnDoi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDoi.setText("ĐỔI");
        btnDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMKCu)
                                .addComponent(lblMKMoi)
                                .addComponent(lblXNMK))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtXNMK, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTaiKhoan)
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaiKhoan)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMKCu)
                    .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMKMoi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXNMK)
                    .addComponent(txtXNMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoi))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiActionPerformed
        // TODO add your handling code here:
        
		String id = DangNhap.id_user;
		String mkCu = txtMKCu.getText();
		String pass_i = DangNhap.pass_id;
		String mkMoi = txtMKMoi.getText();
		String XNMK = txtXNMK.getText();
		String check = "SELECT * FROM NhanVien WHERE maNV = '" + id + "'";
		try {
			stmt = conn.prepareCall(check);
			rs = stmt.executeQuery();
			if (rs.next()) {
				if (mkCu.equalsIgnoreCase(pass_i)) {
					if (mkMoi.equals("")) {
						JOptionPane.showMessageDialog(null, "Bạn Chưa Nhập Mật Khẩu Mới", "Lỗi",
								JOptionPane.ERROR_MESSAGE);
					} else if (kiemTraDL()) {
						if (mkMoi.equalsIgnoreCase(XNMK)) {
							String sql = "UPDATE NhanVien SET matKhau=? WHERE maNV=?";
							stmt = conn.prepareCall(sql);
							stmt.setString(1, mkMoi);
							stmt.setString(2, id);
							stmt.executeUpdate();
							JOptionPane.showMessageDialog(null, "Mật Khẩu Đã Được Thay Đổi Thành Công", "Thành Công",
									JOptionPane.INFORMATION_MESSAGE);
							this.setVisible(false);

						} else {
							JOptionPane.showMessageDialog(null, "Mật Khẩu Mới Không Khớp", "Lỗi",
									JOptionPane.ERROR_MESSAGE);
						}

					}

				} else {
					JOptionPane.showMessageDialog(null, "Mật Khẩu Cũ Không Đúng,Vui Lòng Thử Lại", "Lỗi",
							JOptionPane.ERROR_MESSAGE);
				}

			} else {

				JOptionPane.showMessageDialog(rootPane, "Bạn Chưa Đăng Nhập", "Lỗi", JOptionPane.ERROR_MESSAGE);

			}
		} catch (SQLException ex) {
			// Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnDoiActionPerformed
    
    
	/**
	 * KIỂM TRA DỮ LIỆU.
	 * 
	 * @return
	 */
	public boolean kiemTraDL() {
		String pw = txtMKMoi.getText().trim();

		String pass = "^.*(?=.{8,})(?=..*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$";
		if (!(pw.length() > 0 && pw.matches(pass))) {
			JOptionPane.showMessageDialog(null,
					"Lỗi : Nhập sai định dạng mật khẩu!!!\nMật khẩu chứa ít nhất là 8 ký tự\nTrong đó có ít nhất 1 ký tự số từ 0-9, 1 ký tự chữ thường\n1 ký tự chữ hoa, 1 ký tự đặc biệt như: @#$%^");
			return false;
		}
		return true;
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoi;
    private javax.swing.JLabel lblMKCu;
    private javax.swing.JLabel lblMKMoi;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblXNMK;
    private javax.swing.JPasswordField txtMKCu;
    private javax.swing.JPasswordField txtMKMoi;
    private javax.swing.JTextField txtTK;
    private javax.swing.JPasswordField txtXNMK;
    // End of variables declaration//GEN-END:variables
}
