/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Form;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JFrame;

import Jpanel_Form_QuanLy.QuanLyNV;
import Jpanel_Form_QuanLy.QuanLyXeMay;
import Jpanel_Form_QuanLy.ThongKe;
import Jpanel_Form_QuanLy.QuanLyHoaDon;

/**
 *
 * @author phanb
 */
public class TrangChuQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuQuanLy
     */
    public TrangChuQuanLy() {
        initComponents();
        setLocationRelativeTo(null);
        TrangChu panelf = new TrangChu();
        mainpanel1.removeAll();
        mainpanel1.add(panelf);
        mainpanel1.validate();
        txtChao1.setText(DangNhap.ten_ad);
        Dimension DimMax = Toolkit.getDefaultToolkit().getScreenSize();
        setMaximumSize(DimMax);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        lblLogo1 = new javax.swing.JLabel();
        lblChao1 = new javax.swing.JLabel();
        txtChao1 = new javax.swing.JTextField();
        btnTrangChu1 = new javax.swing.JButton();
        btnQLNV = new javax.swing.JButton();
        btnQLXe = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnTimKiem1 = new javax.swing.JButton();
        btnHoTro1 = new javax.swing.JButton();
        btnDoiMK1 = new javax.swing.JButton();
        btnDangXuat1 = new javax.swing.JButton();
        mainpanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_big/Logo.PNG"))); // NOI18N

        lblChao1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblChao1.setText("Xin chào");

        txtChao1.setEditable(false);
        txtChao1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnTrangChu1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTrangChu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Home-icon.png"))); // NOI18N
        btnTrangChu1.setText("TRANG CHỦ");
        btnTrangChu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrangChu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChu1ActionPerformed(evt);
            }
        });

        btnQLNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Manager-icon (1).png"))); // NOI18N
        btnQLNV.setText("QUẢN LÝ NHÂN VIÊN");
        btnQLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });

        btnQLXe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnQLXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/motorcyclist-icon (1).png"))); // NOI18N
        btnQLXe.setText("QUẢN LÝ XE MÁY");
        btnQLXe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLXeActionPerformed(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Actions-bookmark-new-list-icon.png"))); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnTimKiem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTimKiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/chart-search-icon.png"))); // NOI18N
        btnTimKiem1.setText("QUẢN LÝ HÓA ĐƠN");
        btnTimKiem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem1ActionPerformed(evt);
            }
        });

        btnHoTro1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnHoTro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Actions-help-about-icon.png"))); // NOI18N
        btnHoTro1.setText("HỖ TRỢ");
        btnHoTro1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHoTro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoTro1ActionPerformed(evt);
            }
        });

        btnDoiMK1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDoiMK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/modify-key-icon.png"))); // NOI18N
        btnDoiMK1.setText("ĐỔI MẬT KHẨU");
        btnDoiMK1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDoiMK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMK1ActionPerformed(evt);
            }
        });

        btnDangXuat1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDangXuat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Log-Out-icon.png"))); // NOI18N
        btnDangXuat1.setText("ĐĂNG XUẤT");
        btnDangXuat1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangXuat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuat1ActionPerformed(evt);
            }
        });

        mainpanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainpanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogo1)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblChao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtChao1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTrangChu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoTro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoiMK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangXuat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(mainpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblLogo1)
                        .addGap(24, 24, 24)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChao1)
                            .addComponent(txtChao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTrangChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQLXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHoTro1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoiMK1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDangXuat1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(mainpanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuat1ActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangXuat1ActionPerformed

    private void btnDoiMK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMK1ActionPerformed
        // TODO add your handling code here:
        DoiMatKhau pnl = new DoiMatKhau();
        pnl.setVisible(true);
        pnl.setResizable(false);
        pnl.setLocationRelativeTo(null);
        pnl.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnDoiMK1ActionPerformed

    private void btnHoTro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoTro1ActionPerformed
        // TODO add your handling code here:
        HoTro pnl = new HoTro();
        mainpanel1.removeAll();
        mainpanel1.add(pnl);
        mainpanel1.validate();
    }//GEN-LAST:event_btnHoTro1ActionPerformed

    private void btnTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem1ActionPerformed
        // TODO add your handling code here:
        QuanLyHoaDon pnl = new QuanLyHoaDon();
        mainpanel1.removeAll();
        mainpanel1.add(pnl);
        mainpanel1.validate();
    }//GEN-LAST:event_btnTimKiem1ActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        ThongKe pnl = new ThongKe();
        mainpanel1.removeAll();
        mainpanel1.add(pnl);
        mainpanel1.validate();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        // TODO add your handling code here:
        QuanLyNV panel = new QuanLyNV();
        mainpanel1.removeAll();
        mainpanel1.add(panel);
        mainpanel1.validate();
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnTrangChu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChu1ActionPerformed
        // TODO add your handling code here:
        TrangChu pnl = new TrangChu();
        mainpanel1.remove(pnl);
        mainpanel1.add(pnl);
        mainpanel1.validate();
    }//GEN-LAST:event_btnTrangChu1ActionPerformed

    private void btnQLXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLXeActionPerformed
        // TODO add your handling code here:
        QuanLyXeMay pnl = new QuanLyXeMay();
        mainpanel1.removeAll();
        mainpanel1.add(pnl);
        mainpanel1.validate();
    }//GEN-LAST:event_btnQLXeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat1;
    private javax.swing.JButton btnDoiMK1;
    private javax.swing.JButton btnHoTro1;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLXe;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTimKiem1;
    private javax.swing.JButton btnTrangChu1;
    private javax.swing.JLabel lblChao1;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JPanel mainpanel1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txtChao1;
    // End of variables declaration//GEN-END:variables
}
